-- m_qureshi — run, one-hop people, allow-list additions, and facts.
-- Apply before m_qureshi-02-edges-contexts.sql and m_qureshi-03-source-status.sql.
PRAGMA foreign_keys = ON;
BEGIN;

INSERT INTO run (id,started_at,execution_ctx,notes) VALUES
 ('run_ingest_qureshi_20260903','2026-09-04T01:10:00Z','operator_machine',
  'Content ingest for m_qureshi. Per-person store; completion summary is finalized in m_qureshi-03-source-status.sql.');

-- Shared one-hop people are merge-safe by contract.
INSERT OR IGNORE INTO person
 (id,is_member,display_name,name_respelling,seniority_tier,career_start_decade,
  prominence_tier,prominence_basis,created_run) VALUES
 ('p_will_manidis',0,'Will Manidis',NULL,NULL,NULL,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('p_tyler_cowen',0,'Tyler Cowen',NULL,NULL,NULL,NULL,NULL,'run_ingest_qureshi_20260903');

-- New source rows discovered from confirmed first-party pages or explicitly supplied probes.
-- Existing roster rows (substack_rss, personal_site, github_api, x_profile, offsite) remain untouched.
INSERT OR IGNORE INTO person_identity
 (person_id,source_id,url,handle,role,tier,corroboration,http_status,measured_at,notes) VALUES
 ('m_qureshi','personal_rss','https://nabeelqu.co/rss','nabeelqu','feed','GREEN',
  '["linked_from_own_canonical"]',NULL,'2026-09-03',
  'Known valid but title-only RSS; deliberately not fetched because the confirmed Substack feed has the same catalog with full bodies.'),
 ('m_qureshi','github_activity','https://api.github.com/repos/nqureshi/ev-winners/commits','nqureshi','api','GREEN',
  '["linked_from_own_canonical","api_name_field_matches"]',200,'2026-09-03',
  'Repository activity under the already-confirmed nqureshi account; queried with a September 2026 date bound.'),
 ('m_qureshi','github_chess_trainer','https://api.github.com/repos/nqureshi/chess-trainer/readme','nqureshi','api','GREEN',
  '["linked_from_own_canonical","api_name_field_matches"]',200,'2026-09-03',
  'README API for a repository owned by the already-confirmed nqureshi account.'),
 ('m_qureshi','x_session','https://x.com/nabeelqu','nabeelqu','canonical','SESSION',
  '["api_name_field_matches","bio_backlink_to_canonical"]',200,'2026-09-03',
  'Read-only operator session. Timeline, search results, and following list were read; no write affordance was used.'),
 ('m_qureshi','linkedin_session','https://www.linkedin.com/in/nabeelqu','nabeelqu','canonical','SESSION',
  '["linked_from_own_canonical","display_name_matches"]',200,'2026-09-03',
  'The exact slug was first found in the Contact block of nabeelqu.co, then read in the existing operator session. Personalized degree markers and recommendation rails were discarded.'),
 ('m_qureshi','linkedin_wayback','http://web.archive.org/web/20260123092938/https://www.linkedin.com/in/nabeelqu','nabeelqu','archive','GREEN',
  '["linked_from_own_canonical","display_name_matches"]',200,'2026-09-03',
  'Wayback availability API returned snapshot 20260123092938. Slug was attested from his own canonical site before any LinkedIn request.'),
 ('m_qureshi','dialectic_50','https://dialectic.fm/tyler-nabeel',NULL,'canonical','GREEN',
  '["subject_self_identifies"]',200,'2026-09-03',
  'Full public transcript dated 2026-06-29; the site identifies both speakers and labels Nabeel turns throughout.'),
 ('m_qureshi','newstatesman','https://www.newstatesman.com/science-tech/2026/05/art-against-the-machine',NULL,'canonical','METERED',
  '["subject_self_identifies"]',200,'2026-09-03',
  'Byline and opening paragraphs are public; the rest is a subscriber-only article and was not bypassed.'),
 ('m_qureshi','uncensored_toc','https://leanpub.com/uncensored',NULL,'negative_probe','GREEN',
  '[]',200,'2026-09-03','Contributor/table-of-contents absence probe explicitly requested by the ingest prompt.'),
 ('m_qureshi','openlibrary','https://openlibrary.org/search/authors.json?q=Nabeel%20Qureshi',NULL,'negative_probe','GREEN',
  '[]',NULL,'2026-09-03','Negative book-author probe; the current request failed to connect, so no result was imported.');

INSERT INTO fact
 (id,subject_id,text,provenance_class,trust_class,source_url,source_host,source_date,
  observed_at,composed_from,search_first_page,via_edge_type,via_person_id,run_id) VALUES

-- Full-body Substack corpus. Fourteen items, not a rolling-window estimate.
 ('f_qureshi_001','m_qureshi','The Substack feed exposes 14 complete essay bodies, not title stubs, from 2019-12-15 through 2026-05-03. The measured publication counts are 1 in 2019, 4 in 2020, 1 in 2022, 3 in 2023, 2 in 2024, 2 in 2025, and 1 in 2026. The 410,253-byte feed is the complete known essay corpus and is stronger than the title-only feed on his own domain.','self_published','subject_authored','https://nabeelqu.substack.com/feed','nabeelqu.substack.com','2026-05-03','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_002','m_qureshi','In "What Makes Art Great?" he treats surprise and exact observed detail as core properties of durable writing. His contrast is practical: frontier models can be excellent at code and mathematics yet still fail to produce an essay or poem he finds genuinely interesting; Shakespeare remains the standard because the reader is repeatedly destabilized.','self_published','subject_authored','https://nabeelqu.substack.com/p/what-makes-art-great','nabeelqu.substack.com','2026-05-03','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_003','m_qureshi','His "Principles" essay separates creation from editing: produce material without policing its quality, then switch modes and shape it. He describes writing as a way to discover thought, not merely to transcribe a conclusion already formed.','self_published','subject_authored','https://nabeelqu.substack.com/p/principles','nabeelqu.substack.com','2025-01-12','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_004','m_qureshi','He finished all seven volumes of Proust''s In Search of Lost Time—about 3,000 pages—over roughly six months. He argues that the final volume supplies the payoff and makes the apparent digressions cohere; the essay is close reading by someone who completed the whole sequence.','self_published','subject_authored','https://nabeelqu.substack.com/p/on-reading-prousts-in-search-of-lost','nabeelqu.substack.com','2025-12-18','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_005','m_qureshi','His 2019 Proust reading notes contain an unusually actionable note-taking rule: first write from memory about what actually struck you, without consulting the book; add quotations and references later. He says prose notes should become a growing body that can later be lightly edited into publishable work.','self_published','subject_authored','https://nabeelqu.substack.com/p/reading-notes-lost-time','nabeelqu.substack.com','2019-12-15','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_006','m_qureshi','In his 2020 education essay he uses chess as a model of learned intuition: much of the knowledge is position-specific, built by repeated exposure to lines of force and weak points rather than a portable verbal theory. This is the earlier problem the later endgame kata trainer operationalizes.','self_published','subject_authored','https://nabeelqu.substack.com/p/education','nabeelqu.substack.com','2020-06-21','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_007','m_qureshi','"Notes on Puzzles" connects chess puzzles, mathematical problem solving, and startup founding through the practice of decomposing a hard problem and recognizing reusable structures.','self_published','subject_authored','https://nabeelqu.substack.com/p/notes-on-puzzles','nabeelqu.substack.com','2023-07-11','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_008','m_qureshi','His 36,000-character "Reflections on Palantir" is a first-person account of the company and of his work there, with particular attention to health and biology. It is the longest item in the full-body feed and materially grounds the Palantir part of his career.','self_published','subject_authored','https://nabeelqu.substack.com/p/reflections-on-palantir','nabeelqu.substack.com','2024-10-15','2026-09-04T01:25:50Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),

-- Canonical site, rendered in a real browser through the legitimate Vercel challenge.
 ('f_qureshi_009','m_qureshi','His canonical site describes him as an entrepreneur, writer, and researcher based in New York City. It says he is building a stealth startup, previously worked at Palantir on health and biology, and is a Visiting Scholar studying AI at the Mercatus Center. The startup is deliberately not identified here.','self_published','subject_authored','https://nabeelqu.co/','nabeelqu.co','2026-09-03','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_010','m_qureshi','The site''s "More About Me" section says he grew up in England, studied PPE at Oxford with concentrations including Development Economics and later Wittgenstein, interned at the Bank of England in summer 2008, was a founding employee and VP of business development at GoCardless, and later led enterprise work in public health at Palantir. The 2008 internship places his career start in the 2000s.','self_published','subject_authored','https://nabeelqu.co/','nabeelqu.co','2026-09-03','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_011','m_qureshi','The canonical site exposes dedicated links for his books, reading lists, movies, and principles alongside the essay archive. Reading is not a generic inferred interest: it is a first-class section of the site and is supported by the complete Proust essays.','self_published','subject_authored','https://nabeelqu.co/','nabeelqu.co','2026-09-03','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_012','m_qureshi','The canonical site''s Interviews table links the 2026-06-29 Dialectic conversation with Tyler Cowen and an earlier Dialectic episode at /nabeel-qureshi. Its Contact block directly links linkedin.com/in/nabeelqu; that first-party link attests the LinkedIn slug before either the live profile or its archive was fetched.','self_published','subject_authored','https://nabeelqu.co/','nabeelqu.co','2026-09-03','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),

-- GitHub account and activity. Real handle nqureshi; the denied nabeelqu account was never fetched.
 ('f_qureshi_013','m_qureshi','GitHub API account nqureshi names Nabeel Qureshi, locates him in New York City, and reports 25 public repositories, 68 followers, and an account created 2012-05-20. Repositories include SARS-CoV-2 genome analysis, Emergent Ventures search tools, and chess software.','self_published','subject_authored','https://api.github.com/users/nqureshi','api.github.com','2026-09-03','2026-09-04T01:40:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_014','m_qureshi','GitHub records exactly 11 commits on 2026-09-03 across two repositories: 10 in ev-winners and 1 in the archived ev-search-python repository. The user record was updated that day and ev-winners was pushed at 03:18 UTC, establishing live September 2026 activity.','self_published','subject_authored','https://api.github.com/repos/nqureshi/ev-winners/commits?since=2026-09-01T00:00:00Z','api.github.com','2026-09-03','2026-09-04T01:40:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_015','m_qureshi','The chess-trainer repository calls itself a Chess Endgame Kata Trainer: a web app for repeatedly drilling Lucena, Philidor, and king-and-pawn endings against Stockfish at depth 20+, with instant reset and position evaluation. The repository description says it was fully vibe-coded with Claude Code. It closes the practice loop posed in his 2020 education essay.','self_published','subject_authored','https://github.com/nqureshi/chess-trainer/blob/master/README.md','github.com','2025-07-01','2026-09-04T01:40:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),

-- X profile, live posts, relationship search, and the measured partial follow walk.
 ('f_qureshi_016','m_qureshi','The API mirror for @nabeelqu reports display name "Nabeel S. Qureshi", bio "make yourself proud", location NYC, backlink nabeelqu.co, 37,925 followers, 890 following, and 9,116 posts. The roster''s 37,922 basis has drifted by three; prominence is intentionally not re-baselined.','self_published','subject_authored','https://api.fxtwitter.com/nabeelqu','api.fxtwitter.com','2026-09-03','2026-09-04T01:50:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_017','m_qureshi','His newest X post read on 2026-09-03 says progress in AI should increase our respect for poets and writers, who in his view remain well ahead of frontier-model output. It extends the art essay''s argument into a same-day, current signal.','self_published','subject_authored','https://x.com/nabeelqu/status/2095645993450553838','x.com','2026-09-03','2026-09-04T01:55:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_018','m_qureshi','On 2026-08-31 he wrote that people resist thinking through what happens if AI or swarms become genuinely strong. Together with the 2026-09-03 post, this makes the X surface measured active, not quiet or challenge-induced unknown.','self_published','subject_authored','https://x.com/nabeelqu/status/2094458772915626489','x.com','2026-08-31','2026-09-04T01:55:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_019','m_qureshi','X following graph, PARTIAL: two passes used real wheel events and selectors scoped to primaryColumn, with a reload between passes. Both silently stopped at the same 70 of 890 claimed accounts (7.9%): tszzl, noampomsky, patio11, simonsarris, esyudkowsky, michael_nielsen, robinhanson, nickcammarata, alexeyguzey, isabelunraveled, startingfromnix, atabarrok, richardmcngo, tylercowen, typedfemale, gbrl_dick, danielgross, byrnehobart, artirkel, krishnanrohit, sandersted, jabaluck, architectonyx, jack_w_lindsey, natpurser, joaneleanor_, aiamblichus, bronsonschoen, stevegraham, ryangreenblatt, scaling01, maskedtorah, dylanbowmansf, nickacaputo, pnwprincess23, stephenskolnick, acerfur, arudansk, arctotherium42, cryps1s, stephenlcasper, thom_wolf, tim_hua_, amystweets, papasmurfffs, bayesian0_0, greghburnham, brendan_mccord, sanjehorah, johnschulman2, noahlebovic, a_karvonen, johnsonmxe, jensenhuang, asparagoid, andrewho03, catboosted, benjaminmmurphy, jconorgrogan, frankieislost, jukan05, eaoppv, davideoks, paulembery, salar, danwilliamsphil, eugyppius1, poastmilque, lukeburgis, weltbuch. The identical Who-to-follow markup outside the primary column was excluded. No absence is asserted for the unreached 820.','self_published','subject_authored','https://x.com/nabeelqu/following','x.com','2026-09-03','2026-09-04T02:00:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_020','m_qureshi','A logged-in X search for from:nabeelqu @eshear returned repeated direct replies, not a single incidental citation. Examples include a 2025-05-29 exchange about 5-MeO-DMT, jhanas, and ayahuasca, a 2025-05-02 exchange about wisdom and model responsiveness, and a 2024-03-27 recommendation of Keith Johnstone''s Impro, plus several more replies in February 2024 and November 2024.','self_published','subject_authored','https://x.com/nabeelqu/status/1928289415769534752','x.com','2025-05-29','2026-09-04T02:00:00Z',NULL,1,NULL,NULL,'run_ingest_qureshi_20260903'),

-- LinkedIn: slug first attested by f_qureshi_012, then both archive and session were read.
 ('f_qureshi_021','m_qureshi','The 2026-01-23 archived LinkedIn profile is titled "Nabeel S. Qureshi - Mercatus Center at George Mason University" and reports New York City metropolitan area, 500+ connections, and 2,440 followers in its structured data. It lists Oxford from 2007 to 2010, with specializations including Development Economics and later Wittgenstein.','self_published','subject_authored','http://web.archive.org/web/20260123092938/https://www.linkedin.com/in/nabeelqu','linkedin.com','2026-01-23','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_022','m_qureshi','The live LinkedIn top card, read in an existing operator session on 2026-09-03, names Nabeel S. Qureshi, gives the generic headline "Founder/CEO at Stealth", locates him in the New York City metropolitan area, and reports 2,615 followers and 500+ connections. No startup name is retained; degree-of-connection markers, recommendations, and operator-personalized rails were discarded.','self_published','subject_authored','https://www.linkedin.com/in/nabeelqu','linkedin.com','2026-09-03','2026-09-04T02:03:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),

-- Dialectic #50: the richest voice source in this run.
 ('f_qureshi_023','m_qureshi','Dialectic episode 50, published 2026-06-29 as "Tyler Cowen & Nabeel Qureshi - An Appetite for More", supplies a public roughly 120,000-character transcript with 149 Nabeel-attributed turns. Cowen and Qureshi discuss interviewing, art, friendship, talent, books, and AI.','on_record','publisher','https://dialectic.fm/tyler-nabeel','dialectic.fm','2026-06-29','2026-09-04T01:38:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_024','m_qureshi','In the Dialectic transcript he says the animating question behind his AI writing is power. He explains the art essay by noting that models can excel at programming and mathematics but still cannot write an essay as good as Joan Didion; he wanted an engineer''s account of why beauty resists that progress.','on_record','publisher','https://dialectic.fm/tyler-nabeel','dialectic.fm','2026-06-29','2026-09-04T01:38:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_025','m_qureshi','On taste, he tells Cowen that mentors and models matter because the learner needs faith that there is something real to perceive before perception becomes trained. Later he notes that books are the tokens on which models train, yet human-made books remain especially precious.','on_record','publisher','https://dialectic.fm/tyler-nabeel','dialectic.fm','2026-06-29','2026-09-04T01:38:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),

-- Off-site authored work.
 ('f_qureshi_026','m_qureshi','"Rented Virtue", published 2026-02-10 on Will Manidis''s Minutes, is fully readable and jointly bylined by Will Manidis and Nabeel S. Qureshi. The essay argues that organizations cannot purchase moral legitimacy around otherwise unchanged work; durable constraints come from commitments that are costly to renegotiate.','self_published','subject_authored','https://minutes.substack.com/p/rented-virtue','minutes.substack.com','2026-02-10','2026-09-04T01:30:00Z',NULL,0,'co_appearance','p_will_manidis','run_ingest_qureshi_20260903'),
 ('f_qureshi_027','m_qureshi','The public portion of his 2026-05-23 New Statesman essay "Art against the machine" identifies an alleged AI-written regional prize winner and notes that it beat 7,806 entries. Only the opening three paragraphs were readable; the remaining 1,985-word article is subscriber-only, so no claim from the hidden body is imported.','on_record','publisher','https://www.newstatesman.com/science-tech/2026/05/art-against-the-machine','newstatesman.com','2026-05-23','2026-09-04T01:32:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),

-- Cross-corpus absence evidence and book/TOC negatives.
 ('f_qureshi_028','m_qureshi','The current Feld Thoughts archive page contains 5,551 unique post links and zero visible occurrences of Nabeel Qureshi or nabeelqu. The parallel m_feld ingest preserves the stronger historical result: a prior full-body audit of all 5,551 posts also found zero Qureshi, with the explicit caveat that the newer Pagefind index was not queryable headlessly.','inferred','publisher','https://feld.com/archives/','feld.com','2026-09-03','2026-09-04T01:42:00Z','["f_qureshi_001"]',0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_029','m_qureshi','MEASURED ABSENCE, corpora named: all 14 complete bodies in Qureshi''s Substack feed were searched and contain zero occurrences of Brad Feld; the retained full-body audit of all 5,551 Feld Thoughts posts found zero occurrences of Nabeel Qureshi. They share the evidence-backed reading-and-books topic, but no documented public contact was found across those two corpora. This says nothing about a private relationship.','inferred','subject_authored','https://nabeelqu.substack.com/feed','nabeelqu.substack.com','2026-09-03','2026-09-04T01:43:00Z','["f_qureshi_001","f_qureshi_028"]',0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_030','m_qureshi','The current Leanpub page for Uncensored contains no occurrence of Nabeel Qureshi or nabeelqu, while multiple other roster members do appear. This is a measured absence from that contributor/table-of-contents surface only, not evidence about books generally.','on_record','publisher','https://leanpub.com/uncensored','leanpub.com','2026-09-03','2026-09-04T01:44:00Z',NULL,0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_031','m_qureshi','No authored book is established by the reviewed first-party catalog. His canonical site comprehensively lists essays, projects, and interviews but no book, and the 2026 Dialectic transcript discusses writing a book with Tyler Cowen only as a possible future project. This negative does not rely on the Open Library probe, which was unavailable during this run.','inferred','subject_authored','https://nabeelqu.co/','nabeelqu.co','2026-09-03','2026-09-04T01:44:00Z','["f_qureshi_009","f_qureshi_012","f_qureshi_023"]',0,NULL,NULL,'run_ingest_qureshi_20260903'),
 ('f_qureshi_032','m_qureshi','All 14 complete bodies in Qureshi''s Substack feed were searched for Sarah Tavel and contain zero occurrences. The parallel Tavel ingest found the reverse absence across 104 distinct Adventurista posts, not the supplied 113; because this run did not independently recrawl that second corpus, the correction is reported but no Qureshi-to-Tavel no-edge is asserted from it.','inferred','subject_authored','https://nabeelqu.substack.com/feed','nabeelqu.substack.com','2026-09-03','2026-09-04T01:44:00Z','["f_qureshi_001"]',0,NULL,NULL,'run_ingest_qureshi_20260903');

COMMIT;
