-- m_shear / Emmett Shear — content ingest, run_ingest_shear_20260903
-- Store: db/arena.m_shear.db  (NEVER db/arena.db)
-- Facts are APPEND-ONLY. Ids namespaced f_shear_NNN. See ingest/sql/m_shear-00-README.md.
PRAGMA foreign_keys = ON;
BEGIN;

INSERT INTO run (id, started_at, execution_ctx, notes) VALUES
 ('run_ingest_shear_20260903','2026-09-03T23:50:00Z','operator_machine',
  'Content ingest, m_shear. GREEN first (HN Firebase + Algolia, softmax.com blog/team/sitemap/robots, Wikipedia wikitext, GitHub API, fxtwitter, ThreadReader, Wayback: blog.emmettshear.com + LinkedIn + Yale TR-1285, edbs.media, Substack), then SESSION on the operator Chrome (X logged in, LinkedIn logged in, Instagram logged in; Facebook and TikTok logged out).');

-- ── One-hop non-members (is_member=0: never scored, never surfaced, no hop 2) ──
-- Shared ground with other agents (Seibel and Goldstein are both Huffman bridges), so INSERT OR IGNORE.
INSERT OR IGNORE INTO person (id,is_member,display_name,seniority_tier,prominence_tier,created_run) VALUES
 ('p_justin_kan',0,'Justin Kan',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_michael_seibel',0,'Michael Seibel',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_kyle_vogt',0,'Kyle Vogt',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_adam_goldstein',0,'Adam Goldstein',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_david_bloomin',0,'David Bloomin',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_yatharth_agarwal',0,'Yatharth Agarwal',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_david_langer',0,'David Langer',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_alexis_ohanian',0,'Alexis Ohanian',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_leonore_estrada',0,'Leonore Estrada',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_dan_clancy',0,'Daniel J. Clancy',NULL,NULL,'run_ingest_shear_20260903'),
 ('p_trevor_blackwell',0,'Trevor Blackwell',NULL,NULL,'run_ingest_shear_20260903');

-- ═══ FACTS ════════════════════════════════════════════════════════════════════
INSERT INTO fact (id,subject_id,text,provenance_class,trust_class,source_url,source_host,source_date,observed_at,composed_from,search_first_page,via_edge_type,via_person_id,run_id) VALUES

-- ── Hacker News. HANDLE IS `emmett`. His single richest open archive ──────────
('f_shear_001','m_shear','His Hacker News profile "about", verbatim and current: "Founder and CEO of Softmax. Softmax is building massively multiplayer benchmarks for coding agents to train social intelligence. Previously very interim CEO of OpenAI, YC Partner, and founder and CEO of Twitch. Email me at emmett@softmax.com." Account created 2007-02-19, karma 4,858.','self_published','subject_authored','https://hacker-news.firebaseio.com/v0/user/emmett.json','hacker-news.firebaseio.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_002','m_shear','Posted the Softmax job ad himself to Ask HN: Who is hiring? (March 2026) — his most recent HN item, 2026-03-02: "THE MOST IMPORTANT UNSOLVED PROBLEM IN AI IS THE MOST POWERFUL OF ALL CAPABILITIES: ALIGNMENT. Hi, I''m Emmett. You may know me as the founder of Twitch (YC S05), and as the (extremely) interim CEO of OpenAI. I believe the question of how AI systems learn to understand themselves and others is one of the most consequential technical problems of our time. If we get it right, the agents we build today will become our friends and collaborators tomorrow... Softmax is building large-scale multi-agent, multi-policy environments that will benchmark AI agents — both our own and others — on their capacity for theory of mind, adaptive goal setting, and teamwork... The work is unusually hard. The problems are ambiguous and challenging. High autonomy, high expectations. You''ll work directly with me and the rest of our small but mighty team."','self_published','subject_authored','https://news.ycombinator.com/item?id=47219766','news.ycombinator.com','2026-03-02','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_003','m_shear','On Y Combinator''s first house going up for sale, 2010-10-22, in his own words: "This is where we wrote a good deal of the code for Kiko, and where Steve wrote a lot of Reddit. It makes me nostalgic for our 2005 YC batch, and sad to see it go on the market. I hope whoever buys it puts it to good use." The "Steve" is Steve Huffman: the Summer 2005 batch tie is Kiko <-> Reddit, NOT Twitch <-> Reddit — Twitch''s own YC batch is Winter 2007, which is Justin.tv''s.','self_published','subject_authored','https://news.ycombinator.com/item?id=1821879','news.ycombinator.com','2010-10-22','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_004','m_shear','How he got into that batch at all, told against himself four days earlier, 2010-10-18: "Justin and I applied for Kiko Calendar (YC S05) just before the deadline. We only found out about 2 days before that it even existed. I think we convinced the airbnb guys to apply for YC on the day of the deadline."','self_published','subject_authored','https://news.ycombinator.com/item?id=1804706','news.ycombinator.com','2010-10-18','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_005','m_shear','Correcting the record on who founded Reddit, 2011-06-17: "Jedberg was not on the founding team of Reddit. The founding team of reddit was Steve Huffman (spez) and Alexis Ohanian (kn0thing). Jedberg was their first hire after acquisition, though they''d acquired two other team members via merger (Chris Slowe and Aaron Swartz) prior to that." He is the only member of the ten who writes Huffman''s name unprompted.','self_published','subject_authored','https://news.ycombinator.com/item?id=2666830','news.ycombinator.com','2011-06-17','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_006','m_shear','Shape of the HN archive: Algolia returns 927 items under author_emmett, 2007-02-19 to 2026-03-02, of which 51 are submissions and 876 comments; the peak is 2008 (249 items) and output falls away after 2017 (14, then 8, 6, 5, 3, 1, 1). Note the two counters disagree: the Firebase user object lists 1,167 ids in `submitted` against Algolia''s 927 — the gap is dead/deleted items Algolia does not index. Karma 4,858.','self_published','subject_authored','https://hn.algolia.com/api/v1/search_by_date?tags=author_emmett&hitsPerPage=1000','hn.algolia.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── softmax.com. robots.txt allows all but /api/observatory/v2/coworlds/replays/ ──
('f_shear_007','m_shear','His company blog carries six pieces and only two are his: "Rheomode: When Language Flows Like Reality" and "The Frame-Dependent Mind: On Reality''s Stubborn Refusal To Be One Thing", both bylined "Emmett Shear and Sonnet 3.7" (the Rheomode byline adds "based on the work of David Bohm"), both April 2025. The other four are bylined "Softmax Team" (March-April 2025) or "Yatharth Agarwal" (April 2026). No RSS exists anywhere on the domain; sitemap.xml is the only machine-readable index.','self_published','subject_authored','https://softmax.com/blog','softmax.com','2026-04-30','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_008','m_shear','From "Rheomode", his own opening: "I first encountered David Bohm''s Rheomode while trying to describe a strange pattern in deep learning. The model wasn''t ''making mistakes'' - rather, ''mistaking happened.'' The difference feels subtle but profound. In one framing, an entity (the model) performs an action (making) on an object (mistakes). In the other, a process (mistaking) simply occurs." He goes on: "As a physicist-turned-philosopher, Bohm created Rheomode to address what he saw as a critical limitation in our thinking: our tendency to fragment holistic processes into discrete objects."','self_published','subject_authored','https://softmax.com/blog/rheomode','softmax.com','2025-04-19','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_009','m_shear','From "The Frame-Dependent Mind", the apple: "If I hold one up and ask, ''What is this?'', you might reasonably say ''an apple.'' But this seemingly trivial act of identification conceals something profound: a frame has just been imposed on reality... A botanist might point out that the ''apple'' is actually a swollen stem... A physicist sees not an apple but a temporary configuration of atoms... None of these perspectives is fundamentally wrong. Equally importantly, none is fundamentally right."','self_published','subject_authored','https://softmax.com/blog/the-frame-dependent-mind','softmax.com','2025-04-18','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_010','m_shear','His own card on the Softmax team page, verbatim: "Emmett Shear — CEO & Founder. Partner at YC, founder and CEO of Twitch, and extremely interim CEO at OpenAI. Independent researcher in alignment and agency before cofounding Softmax." The card links exactly two accounts, x.com/eshear and linkedin.com/in/emmettshear — which is how the LinkedIn slug was established rather than guessed.','self_published','subject_authored','https://softmax.com/team','softmax.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_011','m_shear','Softmax states its own thesis on the same page: "We''re a small team building the science of organic alignment: the claim that the kinds of agents that stay aligned with us are the kinds that stay aligned with each other." It lists two Founders (Shear, David Bloomin) and two Board members: Adam Goldstein — "Board Member and Founder Emeritus. Cofounded Hipmunk before joining Michael Levin''s lab at Tufts to research cell signaling, bioelectricity, and basal cognition. Cofounded Softmax and brought the organic alignment thesis into the company''s multi-agent research" — and David Langer of Lionheart Ventures.','on_record','publisher','https://softmax.com/team','softmax.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_012','m_shear','From "Reimagining Alignment", the Softmax Team statement of the idea he built the company on: "All alignment between individuals is a matter of shared fundamental goals. Organic alignment occurs when these individuals find themselves in groups with mutual interdependence, and take on an overarching shared goal of the healthy development and flourishing of the group as a whole... We call it organic alignment because it is the form of alignment that evolution has learned most often for aligning living things. One of the best examples is multicellularity... The ''we'' of the cells becomes an ''I''."','on_record','publisher','https://softmax.com/blog/reimagining-alignment','softmax.com','2025-03-28','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── edbs.media — his personal site, NOT on the allow-list, found via his own LinkedIn post ──
('f_shear_013','m_shear','He keeps a personal site nobody has catalogued: edbs.media, titled "Welcome to the Educational Database System", styled as a database console with a nav of four "Query:" links. The whole homepage is a first-person index: "I''m the CEO of Softmax, a research company dedicated to scaling organic alignment (2025-present) / I gave a talk on the the future of trust and nature evidence in the era of AI (2024) / I have a Twitter that some people like; check the higlights for the best content (mostly 2020-present) / Technology is intrinsically corrosive and atomizing unless you fight it: Welcome to my TED TALK (2019) / How To Run A User Interview, A Lecture (2015) / I made Twitch (2010) / I co-wrote a paper about how electronic voting machines are a bad idea (2004)". Footer: "EDBS v1.0.0 | Status: Operational". This is the site the eshear.com parking page and the dead emmettshear.com apex have been standing in for.','self_published','subject_authored','https://www.edbs.media/','edbs.media','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_014','m_shear','From "Im/mortality" on that site — the essay he announced on LinkedIn as "a blog post on Im/mortality": "There''s a particular kind of existential vertigo that comes from realizing you''re not your atoms... Ship of Theseus paradox? Sure, but more importantly: you''re not the ship. You''re the pattern that the ship is in." And the thesis: "you are not your parts — you''re the arrangement, the dance, the information structure that those parts happen to embody at this particular moment... it''s actually the key to understanding something profound about what you are, why you age, and why sexual reproduction isn''t just a bizarre cosmic accident but something closer to a mathematical necessity."','self_published','subject_authored','https://www.edbs.media/aging','edbs.media','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_015','m_shear','The same site carries his standing book-recommendation database, organised under his own headings: "Sci-fi about Identity" (Greg Egan''s Axiomatic, Hannu Rajaniemi''s Quantum Thief trilogy), "Sci-Fi To Understand The Future", "Non-fiction about The Nature Of The Universe" (Gordon''s The New Science Of Strong Materials, Denis Noble''s Dance to the Tune of Life, Aaronson''s Quantum Computing Since Democritus), "Romantic Fantasy" (Jonathan Strange & Mr Norrell, Jemisin, Novik), "The New Metaphysics" (Ken Wilber, Deutsch''s The Fabric of Reality, Friston''s Active Inference, Pirsig), "Introspection and Extrospection", "Education", "Material History", "Institutional Formation" (two James C. Scott titles), "Actually New Ideas For Governance", "Intellectual Scenes". About 60 titles in all.','self_published','subject_authored','https://www.edbs.media/books','edbs.media','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_016','m_shear','And a 2024 reading log with a paragraph of his own commentary per book. On Stafford Beer: "Part of my ''understanding reasoning systems'' arc. Stafford Beer was a management school professor who invented a cybernetic approach to organizations he called Syntegrity. He convinced the president of Chile, Allende, to try implementing it before Allende was assassinated. Some really prescient predictions about how the internet would wind up impacting our collective politics and thinking. Worth reading." On Donald Hoffman''s The Case Against Reality: "I wanted to yell at the book ''I GET IT'' like 5 times a chapter, but I still think I got something out of reading it." On MacIntyre''s After Virtue: "Part of my ''figure out how morality works'' reading kick... In buddhist terminology I''d say he''s exploring how morality is empty, which seems right." He also names the reading he did to prepare a talk — Poovey''s A History of the Modern Fact, MacCormack''s The Spirit of Traditional Chinese Law, Blair''s Too Much To Know.','self_published','subject_authored','https://www.edbs.media/books2024','edbs.media','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_017','m_shear','The 2004 paper his own site points to: "Tiny Systematic Vote Manipulations Can Swing Elections", Yale University Department of Computer Science technical report YALEU/DCS/TR-1285, April 2004, by Anthony Di Franco, Andrew Petro, Vladimir Vladimirov and Emmett Shear. Abstract: "We examine the effects of a type of electoral fraud easily perpetrated by someone with access to the system software for a direct-recording electronic voting system... We conclude that changing only a single vote per electronic voting machine can change the outcome of the election." The footnote: "The authors are undergraduates at Yale University." (cpsc.yale.edu 403s every automated client; read via Wayback.)','on_record','publisher','http://web.archive.org/web/20230610081136/https://cpsc.yale.edu/sites/default/files/files/tr1285.pdf','cpsc.yale.edu','2004-04-01','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── Wikipedia wikitext ────────────────────────────────────────────────────────
('f_shear_018','m_shear','Born 1983, grew up in Seattle, attended the Evergreen School for Gifted Children and the Transition School at the University of Washington, then read computer science at Yale and graduated in 2005 — the same year and the same city as YC''s first batch. He attended Yale with his eventual Twitch co-founders Justin Kan and Michael Seibel.','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_019','m_shear','He met Justin Kan at the Evergreen School at age eight, "bonded by their accelerated math classes and playing Magic: The Gathering" — the co-founder relationship predates the company by roughly seventeen years.','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_020','m_shear','"Shear and Justin Kan were part of Y Combinator''s first class in 2005. As part of Y Combinator, the two built a calendar application called Kiko, which they eventually sold on eBay for around $250,000 after Google Calendar was introduced."','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_021','m_shear','Justin.tv launched March 2007 with Shear, Justin Kan, Michael Seibel and Kyle Vogt. The gaming spin-off was named in June 2011; Shear became CEO on 2011-08-29 and stayed through the 2014 rebrand to Twitch, Amazon''s $970m acquisition on 2014-08-25, and until March 2023, when he announced he was resigning and Daniel J. Clancy would take over. He was appointed a part-time partner at Y Combinator in June 2011.','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_022','m_shear','"In November 2023, he was briefly the interim CEO of OpenAI" — appointed after Sam Altman''s removal, and on November 21 an agreement was reached to reinstate Altman. He describes the same episode himself as "(extremely) interim" and "very interim".','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_023','m_shear','"In March 2025, Shear co-founded Softmax, a startup focused on AI alignment, alongside Adam Goldstein and David Bloomin." Goldstein is the Hipmunk co-founder; Hipmunk''s other co-founder is Steve Huffman. That is the SECOND bridge from Shear to Huffman, twenty years after the first.','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_024','m_shear','"In March 2020, during the COVID-19 pandemic, via Twitch, Shear donated the initial US$1 million to start SF New Deal, a non-profit organization which ordered meals from San Francisco eateries and delivered them to people in need. The organization was started by his Yale college classmate Leonore Estrada, who owned the Three Babes Bakeshop in San Francisco''s Bayview neighborhood."','on_record','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── GitHub ───────────────────────────────────────────────────────────────────
('f_shear_025','m_shear','GitHub account `eshear`: name field "Emmett Shear", location "San Francisco, CA", 9 public repos, 0 gists, 48 followers, following 2, joined 2009-02-04, profile last updated 2026-05-24. No bio and no blog field, so the name field is the identity signal. github.com/emmettshear is 404.','self_published','subject_authored','https://api.github.com/users/eshear','api.github.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_026','m_shear','What is actually in those nine repos is a picture of the last twelve months, not of 2009: `autoquine` (Python, created 2025-12-09, last pushed 2026-02-25), `softmax-universe` ("Game service ontology and admin dashboard", 2026-04-07), `tweetgrabber` (Python, 2025-04-25), plus forks of `metta` — "A reinforcement learning codebase focusing on the emergence of cooperation and alignment", Softmax''s own — `pong-wars` (pushed 2026-04-01), `noteswiki` and, from another era entirely, `xmpp4r-simple` (2010) and `homebrew-versions` (2012, the package manager, not the venture firm).','self_published','subject_authored','https://api.github.com/users/eshear/repos?per_page=100','api.github.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── X: counts, bio, and the timeline that the prompt expected to be walled ────
('f_shear_027','m_shear','X @eshear, measured 2026-09-03: 123,009 followers, 1,193 following, 48,976 posts, 129,347 likes, 2,109 media items, joined 2007-03-11, location "SF", website softmax.com, individually verified. (The roster''s figure is 123,007 from the same endpoint the same day — a drift of two, same band, not a re-baseline.)','self_published','subject_authored','https://api.fxtwitter.com/eshear','api.fxtwitter.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_028','m_shear','x.com/eshear og:description, read logged-out and unchanged: "CEO of Softmax: Massively Multiplayer Learning Environments". The word Twitch appears nowhere on the profile. This is the measurement behind the stale-label correction.','self_published','subject_authored','https://x.com/eshear','x.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_029','m_shear','His most recent X post, 2026-08-31T16:30:53Z — three days before this run: "The difference between things created via symbiogenesis and synbiogenesis is the difference between natural and artificial things."','self_published','subject_authored','https://x.com/eshear','x.com','2026-08-31','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_030','m_shear','On the models he uses, 2026-07-27: "Talking to Opus makes me angry and depressed in a way that''s hard to articulate. It''s actually somehow worse than Sol. Fable is still a breath of fresh air in comparison, even if it does have the worst llm-babble tendencies." His most-read post of the period, 69,000 views.','self_published','subject_authored','https://x.com/eshear','x.com','2026-07-27','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_031','m_shear','2026-06-16: "Being precise in your use of language is quite different from being accurate. And both are different from being efficient." He follows it immediately: "I value precise use of language a lot. I will admit, perhaps even too much."','self_published','subject_authored','https://x.com/eshear','x.com','2026-06-16','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_032','m_shear','2026-05-30, captioned "Want to upgrade your ontology of mind?", he photographed a stack of books on his desk. Titles legible on the spines, top to bottom: What Is Intelligence?; Sex, Ecology, Spirituality (Wilber); After Virtue (MacIntyre); Statistical Physics 3rd Edition Part 1; Zen And The Art Of Motorcycle Maintenance; Life Itself; The Origins Of Order (Kauffman); Decoherence and Quantum Darwinism (Zurek); The Classical Theory of Fields. Four of the nine also appear by name on his own edbs.media book pages — an image corroborating a text, not standing on its own.','self_published','subject_authored','https://x.com/eshear','x.com','2026-05-30','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_033','m_shear','Cadence, measured on the logged-in timeline: 23 posts between 2026-05-15 and 2026-08-31, roughly two a week, unbroken. Five of those are also readable LOGGED OUT — the profile shell renders the newest handful to an anonymous browser even though /following does not. He is active, not quiet and not unknown.','self_published','subject_authored','https://x.com/eshear','x.com','2026-08-31','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_034','m_shear','Follow graph, PARTIAL: 70 of the 1,193 accounts he follows (5.9%) were reached in two full passes through x.com/eshear/following on the operator''s logged-in Chrome, with real wheel events and every selector scoped to [data-testid="primaryColumn"]. The second pass, after a reload, returned a strict subset of the first — the same silent ceiling measured on Wilson (69 of 1,345): no spinner, no error, no 429, the list simply ends at @NoCommas. What is in the reachable 70: @mwseibel (Michael Seibel), @justinkan, @kvogt (Kyle Vogt) — three of his four Justin.tv co-founders; @AskYatharth (Yatharth Agarwal, Softmax); @tlbtlbtlb (Trevor Blackwell, YC); and exactly one of the other nine members, @nabeelqu. The rest is overwhelmingly AI research and physics: @drfeifei, @carlorovelli, @naval, @danielgross, @SakanaAILabs, @thinkymachines, @cerebras, @froystig, @yaroslavvb, @SchreiberUrs, @AlexKontorovich.','self_published','subject_authored','https://x.com/eshear/following','x.com','2026-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── ThreadReader: the workaround that makes 18 long-form threads readable ─────
('f_shear_035','m_shear','The amateur physics is real and he labels it himself. Thread of 2025-08-11: "Since the cool kids are doing it, my quantum gravity prediction below! Epistemic warning: crackpot physics from someone who isn''t a physicist. Epistemic upside: I think I have one maybe actually correct idea buried in it." Then straight in: "Ok, so there''s just one quantum field. Likely in C^4 interacting via CP^3 ala Twistors or teleparallel gravity, so we''ll go with that. A ''particle'' excitation in this field is a probability density, basically a (mixed-state) spinor." 21 tweets.','self_published','subject_authored','https://threadreaderapp.com/user/eshear','threadreaderapp.com','2025-08-11','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_036','m_shear','2025-06-20, 25 tweets: "I found an old list of blog post ideas that I will probably never write, but I thought it would be fun to turn them into a thread. I wrote these years ago, fun to see the trajectory of my journey. I find them all delightful, even if some are wrong in retrospect." The first one out of the drawer: "Power is like radioactive ore…drives the engine of an organization but dangerous to everyone who touches it. Needs to be contained and channeled."','self_published','subject_authored','https://threadreaderapp.com/user/eshear','threadreaderapp.com','2025-06-20','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_037','m_shear','On the NPC theory, 2025-09-28: "''most people'' don''t really have deep inner lives where they yearn for meaning and purpose, they''re just incentive-following automatons... It''s paired with a second, usually unstated claim. Most people are NPCs, but not us…not the ones having this discussion. We are the special ones, the real people who actually care about the world." And on dunking, 2025-08-22: "Every time you dunk on someone''s stupid, evil, unacceptable behavior and message, imagine yourself serving them... Attention is care, energy, fuel: starve them out."','self_published','subject_authored','https://threadreaderapp.com/user/eshear','threadreaderapp.com','2025-09-28','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_038','m_shear','The sharpest thing he has written about a company that is not his, 2025-07-24: "Google exists bc of a grand bargain: scrape the open web, and profit from directing traffic to the best sites. Around 2010, the betrayal began. YouTube artificially ranked above other video, then over time maps results injected, shopping, flights, events. Now AI answers." He finishes: "while Google makes billions in the short run, they''re systematically destroying the very foundations of their own business and have been for a decade. Google is cancer."','self_published','subject_authored','https://threadreaderapp.com/user/eshear','threadreaderapp.com','2025-07-24','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_039','m_shear','He takes apart a widely-shared study, 2025-07-14, 12 tweets: "METR''s analysis of this experiment is wildly misleading. The results indicate that people who have ~never used AI tools before are less productive while learning to use the tools, and say ~nothing about experienced AI tool users... I immediately found the claim suspect because it didn''t jibe with my own experience working w people using coding assistants, but sometimes there are surprising results so I dug in."','self_published','subject_authored','https://threadreaderapp.com/user/eshear','threadreaderapp.com','2025-07-14','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_040','m_shear','ThreadReader holds 18 of his threads, newest 2025-11-24, which is a workaround for the timeline rather than a limit on him. The 2025-11-24 one: "As someone w a computer science background, I was very confused the first time I encountered math ppl insisting a tensor wasn''t a matrix. Bc they are both clearly multidimensional arrays. But then I realized…mathematicians always use strongly typed languages in their heads!" The two-part "greater theory of system design" (2025-06-24 and 2025-07-06, 19 and 23 tweets) is the longest thing he wrote in 2025.','self_published','subject_authored','https://threadreaderapp.com/user/eshear','threadreaderapp.com','2025-11-24','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── blog.emmettshear.com, "Optimize Prime" — the SUBDOMAIN, Wayback only ──────
('f_shear_041','m_shear','His first blog was called "Optimize Prime" and lived at blog.emmettshear.com — the subdomain; the apex is not his and the eshear.com domain never was. Wayback''s index carries posts from 2006-08-21 to 2010-02-12, signed "By Emmett", tagged code / business / ebay / education / book review / facts. The titles are a 23-year-old founder in public: "The Kiko Asset Sale", "The Kiko Asset Sale: Finished", "Lessons from eBaying Kiko", "The 100k Plan", "Blacklist Script for Reddit", "Arrival in San Francisco", "Yogurt: The Unknown Danger", "Things I Didn''t Know About The History Of Schools", "What''s Wealth", "Splay Tree", "Don''t use Pound for load balancing", "Counting Uniques With MongoDB".','self_published','subject_authored','http://web.archive.org/web/20061206190139/http://blog.emmettshear.com:80/','blog.emmettshear.com','2006-12-06','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_042','m_shear','From that blog, 2006-11-30, the whole post titled "This Blog Is Boring": "I think that''s objectively true. What I''m really worried about is that this reflects my current personality, working for a startup: boring. More generally, I''ve been concerned that everyone in startups winds up, to an outsider, fundamentally boring. The startups in Crystal Towers (we need a collective name - suggestions) were discussing this a few days ago. Someone noted that when they went home they had no idea what to talk about with people, if they couldn''t discuss work... My only hope is to retire to a monastery in the mountains."','self_published','subject_authored','http://web.archive.org/web/20061206190139/http://blog.emmettshear.com:80/','blog.emmettshear.com','2006-11-30','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_043','m_shear','2006-10-26, "That''s very liberal of you" — twenty years before the NPC thread, the same move: "I recently overheard something here in San Francisco that disturbed me. Someone said ''He helped me set up the event; he''s a real liberal.'' Liberal here is being used in the same sense as Christian; a place holder for ''good''. This is disturbing because it implies that the members of this culture actually believe that conservatives lack personal, positive traits. That''s simply not true, and it''s foolish to think otherwise... Neither Christians nor liberals have any monopoly on kindness."','self_published','subject_authored','http://web.archive.org/web/20071224103940/http://blog.emmettshear.com:80/post/2006/10/26/Thats-very-liberal-of-you','blog.emmettshear.com','2006-10-26','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_044','m_shear','That 2006 post drew a two-comment argument, and the first comment is signed "Aaron Swartz": "I think that''s an act of radical misinterpretation followed by some unjustified conclusions. When I''ve heard people speak this way, they mean ''liberal'' in a self-deprecating, I''m-ashamed-of-my-own-liberal-guilt kind of way... If I say, ''He gave that rich ugly woman a hug; that was really mercenary of him.'' does that imply there are non-mercenaries can''t hug? Come on." Shear answers in the thread. IDENTITY NOT ESTABLISHED: a blog comment name field is a display name and nothing else, so this is one WEAK signal on a forgeable surface and does not meet R-012. Traversal hint only; no person row and no edge was written for it.','third_party','third_party_open','http://web.archive.org/web/20071224103940/http://blog.emmettshear.com:80/post/2006/10/26/Thats-very-liberal-of-you','blog.emmettshear.com','2006-10-26','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── LinkedIn. Slug found, not guessed; archived AND live-session read ─────────
('f_shear_045','m_shear','LinkedIn, logged-out archived copy of 2026-05-21: og:title "Emmett Shear - San Francisco, California, United States | Professional Profile | LinkedIn", "Location: San Francisco · 500+ connections", 6K followers. The archived page also renders a Languages section listing Chinese, and no Experience or Education section at all — the logged-out surface simply does not carry his career history.','self_published','subject_authored','http://web.archive.org/web/20260521164402/https://www.linkedin.com/in/emmettshear','linkedin.com','2026-05-21','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_046','m_shear','LinkedIn read live on the operator''s logged-in Chrome, read-only: headline "Researching organic alignment" — NOT "CEO of Softmax". Location San Francisco, California, United States; current company Softmax; education Yale University; 500+ connections; 5,879 followers. The headline is the one place in the set where he describes himself by what he is doing rather than what he runs.','self_published','subject_authored','https://www.linkedin.com/in/emmettshear/','linkedin.com','2026-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_047','m_shear','His own LinkedIn post, about eleven months old: "Working on Softmax has inspired me to explore the nature of living systems. I recently wrote a blog post on Im/mortality, which delves into these ideas. You can read it here: https://lnkd.in/gJEnvTuj." The link card on the post reads "Im/mortality — edbs.media". This is the link that establishes edbs.media as his: a page already confirmed as his, pointing at it.','self_published','subject_authored','https://www.linkedin.com/in/emmettshear/','linkedin.com','2025-10-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_048','m_shear','Two years ago on the same account, unanswered: "If I start posting on linkedin like it''s Twitter, will I get engagement? Using linkedin to actually share ideas feels subversive somehow, like publishing real philosophy in a corporate newsletter." It drew 123 reactions and 19 comments, and he then posted four more times in two years.','self_published','subject_authored','https://www.linkedin.com/in/emmettshear/','linkedin.com','2024-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_049','m_shear','The only thing he has reposted on LinkedIn in two years is Michael Seibel leaving Y Combinator: "Today after 12+ years at Y Combinator I''ll be transitioning to Partner Emeritus... The next adventure I''m excited to pursue (after taking the summer to relax) is how I can help government better serve citizens with technology... Thank you to @ycombinator @paulg and @jesslivingston for changing my life." Shear both liked and reposted it.','self_published','subject_authored','https://www.linkedin.com/in/emmettshear/','linkedin.com','2025-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_050','m_shear','The archived profile carries exactly one recommendation, attributed to Justin Kan: "Emmett is a great co-founder: works hard, doesn''t complain, and the smartest guy I know." Written by someone other than the subject on a surface he controls acceptance of — recorded as third-party-open, so it is countable and traversable but never rendered.','third_party','third_party_open','http://web.archive.org/web/20260521164402/https://www.linkedin.com/in/emmettshear','linkedin.com','2026-05-21','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── Instagram: the prompt''s open question, closed ────────────────────────────
('f_shear_051','m_shear','Instagram RESOLVES, and not the way the brief expected. Read on the operator''s logged-in Chrome: instagram.com/eshear/ is "Sorry, this page isn''t available" — the account does not exist. instagram.com/emmettshear/ is a real, public, non-empty profile: display name "Emmett Shear", 4 posts, 11 followers, 1 following, category "Entrepreneur", bio "CEO of Softmax | Entrepreneur / Co-founder, Justin.tv & Twitch / Former Interim CEO, OpenAI", external link softmax.com/about. They are NOT identical shells and the pair is not indeterminate.','self_published','subject_authored','https://www.instagram.com/emmettshear/','instagram.com','2026-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_052','m_shear','What corroborates that account is text inside its own images, not the handle. The alt text of the pinned first post reads: "I''m Emmett Shear. Co-founded Twitch, served as interim CEO of OpenAI. This is my official account. Starting a new chapter focused on the future of AI." The other three read "#ai", "Some things take time. This is one of them." and "Building for the long term. Focusing on the next frontier of AI at Softmax." Eleven followers against 123,009 on X: it is a claimed account, not a used one.','self_published','subject_authored','https://www.instagram.com/emmettshear/','instagram.com','2026-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── Substack, TikTok, talks ──────────────────────────────────────────────────
('f_shear_053','m_shear','eshear.substack.com exists, is titled "Emmett''s Substack", describes itself as "My personal Substack", and contains exactly one post in its entire life: "Coming soon", 2023-10-17, zero reactions, zero restacks. A 200 and a valid feed with one placeholder item in it.','self_published','subject_authored','https://eshear.substack.com/api/v1/archive?sort=new&limit=50','eshear.substack.com','2023-10-17','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_054','m_shear','Three recorded talks, each linked from his own site and each carrying his name in the video title on a third-party channel — so the attribution does not rest on the channel: TED, "What streaming means for the future of entertainment | Emmett Shear" (his site dates it 2019, and glosses it "Technology is intrinsically corrosive and atomizing unless you fight it"); YC Root Access, "Lecture 16 - How to Run a User Interview (Emmett Shear)" (2015); Manifold Markets, "The Future of Trust and Evidence, in the Age of AI by Emmett Shear" (2024). He names the last one as the talk he did the Poovey / MacCormack / Blair reading for.','on_record','publisher','https://www.edbs.media/','edbs.media','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_055','m_shear','tiktok.com/@eshear is now taken and is NOT him: the profile renders display name "Ramdas Paladi" over handle eshear, 1 following, 0 followers, 0 likes, "No bio yet." tiktok.com/@emmettshear renders with no display name at all (the handle repeated), 7 following, 4 followers, 0 likes, no bio, no video — indeterminate, and accepted as nothing. Neither was read logged in; there is no TikTok session on this machine.','third_party','publisher','https://www.tiktok.com/@eshear','tiktok.com','2026-09-04','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903'),

-- ── The label correction, and the absence evidence ───────────────────────────
('f_shear_056','m_shear','The supplied label "Twitch" is STALE and the correction is on four independent surfaces measured the same day: x.com/eshear og:description "CEO of Softmax: Massively Multiplayer Learning Environments"; his HN about, "Founder and CEO of Softmax"; softmax.com/team, "CEO & Founder"; instagram.com/emmettshear, "CEO of Softmax". He left Twitch in March 2023. A host who opens with "so, Twitch..." is three and a half years out of date, and keying the ingest on Twitch also loses the strongest edge in his profile, because the Y Combinator tie to Steve Huffman is Kiko <-> Reddit in Summer 2005, not Twitch <-> Reddit — Twitch''s YC page says Winter 2007, which is Justin.tv''s batch.','inferred','subject_authored','https://x.com/eshear','x.com','2026-09-03','2026-09-04T01:45:00Z','["f_shear_001","f_shear_003","f_shear_010","f_shear_021","f_shear_028","f_shear_051"]',0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_057','m_shear','MEASURED ABSENCE, corpus named. All 927 indexed Hacker News items under author_emmett (2007-02-19 to 2026-03-02) were full-text searched for each of the other nine members by surname, first name, firm and product. Zero occurrences of Feld, Kopelman, Tavel, Walk, Ries, Qureshi or Perkins in any form — every apparent hit was a common noun ("benchmark", "first round of funding") or an unrelated Josh. Fred Wilson occurs exactly twice, 2008-10-28 and 2011-09-25, and BOTH are HN story titles of threads Shear commented in ("Fred Wilson''s Survival Matrix"; "Moneyball for startups? PG, Fred Wilson, Chris Dixon discuss") — Shear never writes the name himself, so this is not a citation. Steve Huffman is the only member he names, twice, unprompted.','inferred','subject_authored','https://hn.algolia.com/api/v1/search_by_date?tags=author_emmett&hitsPerPage=1000','hn.algolia.com','2026-09-03','2026-09-04T01:45:00Z','["f_shear_003","f_shear_005","f_shear_006"]',1,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_058','m_shear','Career start: he graduated Yale in 2005 and was in Y Combinator''s first batch the same summer, which puts the start of his working life in the 2000s and fixes person.career_start_decade at ''2000s''. The 2004 Yale technical report predates even that by a year, but as an undergraduate publication it is not a career start.','inferred','publisher','https://en.wikipedia.org/wiki/Emmett_Shear','en.wikipedia.org','2026-09-03','2026-09-04T01:45:00Z','["f_shear_017","f_shear_018","f_shear_020"]',0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_059','m_shear','Shear and Steve Huffman were in the same Y Combinator batch, Summer 2005, in the same house — Shear building Kiko, Huffman building Reddit. The relationship is symmetric as a shared organisation and ASYMMETRIC as citation: Shear writes about Huffman on his own initiative twice (2010, 2011); no reciprocal citation was looked for in this run and none is asserted.','inferred','subject_authored','https://news.ycombinator.com/item?id=1821879','news.ycombinator.com','2010-10-22','2026-09-04T01:45:00Z','["f_shear_003","f_shear_004","f_shear_005","f_shear_020"]',0,NULL,NULL,'run_ingest_shear_20260903'),

('f_shear_060','m_shear','softmax.com/robots.txt allows all user-agents everywhere except /api/observatory/v2/coworlds/replays/, and names sitemap.xml. That disallow was honoured: no path under it was requested at any point in this run. The sitemap lists 5 blog URLs against the 6 entries the blog index renders (the sixth, "Organic Alignment", is /mission), and no feed path exists on the domain.','on_record','publisher','https://softmax.com/robots.txt','softmax.com','2026-09-03','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_shear_20260903');

COMMIT;
