-- m_tavel / Sarah Tavel — content ingest, run_ingest_tavel_20260903
-- Store: db/arena.m_tavel.db  (never db/arena.db)
-- Facts are APPEND-ONLY. Ids namespaced f_tavel_NNN. See ingest/sql/m_tavel-00-README.md.
PRAGMA foreign_keys = ON;
BEGIN;

INSERT INTO run (id, started_at, execution_ctx, notes) VALUES
 ('run_ingest_tavel_20260903','2026-09-03T23:55:00Z','operator_machine',
  'Content ingest, m_tavel. GREEN first (Substack feed+archive API, Medium feed, fxtwitter, EDGAR CIK 0001774645, Every.to transcript, Wayback/Adventurista), then SESSION (LinkedIn, X, Instagram logged in; TikTok, Facebook logged out).');

-- ── One-hop non-members (is_member=0: never scored, never surfaced, no hop 2) ──
-- Benchmark managing members of BCMC VIII, named together in SEC Form 3/4 footnotes.
INSERT OR IGNORE INTO person (id,is_member,display_name,seniority_tier,prominence_tier,created_run) VALUES
 ('p_matt_cohler',0,'Matt Cohler',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_peter_fenton',0,'Peter Fenton',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_bill_gurley',0,'J. William Gurley',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_anyen_hu',0,'An-Yen Hu',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_mitchell_lasky',0,'Mitchell H. Lasky',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_chetan_puttagunta',0,'Chetan Puttagunta',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_steven_spurlock',0,'Steven M. Spurlock',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_eric_vishria',0,'Eric Vishria',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_victor_lazarte',0,'Victor Lazarte',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_miles_grimshaw',0,'Miles Grimshaw',NULL,NULL,'run_ingest_tavel_20260903'),
 -- family, from her own bios and her own posts
 ('p_christine_lemke',0,'Christine Lemke',NULL,NULL,'run_ingest_tavel_20260903'),
 -- former colleagues she names in her own writing
 ('p_ben_silbermann',0,'Ben Silbermann',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_evan_sharp',0,'Evan Sharp',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_john_lilly',0,'John Lilly',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_jeremy_levine',0,'Jeremy Levine',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_philippe_botteri',0,'Philippe Botteri',NULL,NULL,'run_ingest_tavel_20260903'),
 ('p_byron_deeter',0,'Byron Deeter',NULL,NULL,'run_ingest_tavel_20260903');

-- ═══ FACTS ════════════════════════════════════════════════════════════════════
INSERT INTO fact (id,subject_id,text,provenance_class,trust_class,source_url,source_host,source_date,observed_at,composed_from,search_first_page,via_edge_type,via_person_id,run_id) VALUES

-- ── sarahtavel.com (Substack), her live blog. Self-published, subject-authored ──
('f_tavel_001','m_tavel','Stepped back from General Partner to VENTURE PARTNER at Benchmark on 2025-04-29, in her own announcement: "After eight years at Benchmark, I''m shifting to a Venture Partner role. In this new role, I''ll continue to make new investments on behalf of Benchmark, serve on my existing boards, and contribute to Benchmark and our portfolio. What''s changing is my focus and time allocation." Her reason: "for me to best support founders building in AI, I need more space. More space to go AI-native by fully immersing myself in AI tools at the edge, more space to reflect on the last ten years... and maybe even (don''t hold me to this!) more space to think through it all by writing."','self_published','subject_authored','https://www.sarahtavel.com/p/my-new-role-at-benchmark','sarahtavel.com','2025-04-29','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_002','m_tavel','On why Benchmark''s structure demands what it does: "a small equal partnership of no more than six general partners, all generalists, deeply committed to partnering with the most ambitious founders of our generation. With no junior people or platform team, the structure demands total dedication from each partner."','self_published','subject_authored','https://www.sarahtavel.com/p/my-new-role-at-benchmark','sarahtavel.com','2025-04-29','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_003','m_tavel','Co-signed Benchmark''s announcement of Victor Lazarte as General Partner — "Peter, Eric, Sarah, Chetan, and Miles" — and set out the firm''s own definition of itself: "the firm remains defined by the simple, clear model of six equal General Partners, each operating with the autonomy and ownership of a founder in the fullest sense — from compensation to decision making authority... At Benchmark, we strive to offer a radically different level of service and commitment to the founders we serve. Done this way, venture does not scale."','self_published','subject_authored','https://www.sarahtavel.com/p/benchmarks-new-general-partner-victor','sarahtavel.com','2023-07-24','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_004','m_tavel','On performance review design, drawing on both her former employers: "at Pinterest, we had a 2x2 where one axis was ''Impact'', and the other was ''Values''. According to my former Greylock partner John Lilly, at Mozilla they talked about impact across project and company."','self_published','subject_authored','https://www.sarahtavel.com/p/the-mitochondria-in-startups','sarahtavel.com','2023-07-25','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_005','m_tavel','A Pinterest failure told against herself: the growth team rebuilt the new-user experience by studying Instagram''s "like it was a map", shipped something "honestly, weak", and the metrics showed it immediately; the rebuild got deprioritised and "Pinterest went through a period of hyper growth with an underperforming NUX." Months later she signed out of Twitter to look at theirs — "They''d updated it… to something similar to Pinterest''s. The NUX that we knew was under performing."','self_published','subject_authored','https://www.sarahtavel.com/p/dont-fall-into-the-trap-of-taking','sarahtavel.com','2023-07-14','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_006','m_tavel','Her Substack, sarahtavel.com, holds exactly 23 posts across its whole life, 2023-02-22 to 2025-09-03 — about 0.74 posts a month, and bursty: eight of them fall between 2025-01-14 and 2025-09-03, and nothing has been published there in the twelve months since. The masthead changed under her: "Rougher Thoughts by Sarah Tavel" in 2023, "Sarah Tavel''s Newsletter" by 2025.','self_published','subject_authored','https://www.sarahtavel.com/api/v1/archive?sort=new&limit=50&offset=0','sarahtavel.com','2025-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_007','m_tavel','Substack profile bio, verbatim: "Blogging since 2006. Partner @benchmark. formerly: product @pinterest. vc @greylockvc, @bessemervp." Profile created 2023-01-04.','self_published','subject_authored','https://www.sarahtavel.com/api/v1/publication/users/ranked?public=true','sarahtavel.com','2023-01-04','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── medium.com/@sarahtavel — the HTML 403s, the feed does not ─────────────────
('f_tavel_008','m_tavel','Her Medium feed carries ten items, 2023-01-04 to 2024-04-02, opening with "Trying something new — Weekly Thoughts" and closing with "AI Startups: 100x and cheaper"; she cross-posted the same essays to Substack. Nothing has appeared there since 2024-04-02. (medium.com/@sarahtavel returns 403 to automated clients; the feed is the only readable surface, and it is a ten-item window, not a lifetime count.)','self_published','subject_authored','https://medium.com/feed/@sarahtavel','medium.com','2024-04-02','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── X, logged in. Bio/counts/post bodies only; personalization stripped ───────
('f_tavel_009','m_tavel','X bio, verbatim: "Partner at @Benchmark. Student of escaping competition. Formerly product @pinterest. Ball and chain for @cklemke and 🧒🏽👧🏻👶🏻." Location "san francisco", website sarahtavel.com, joined May 2008, 9,417 posts, 1,435 following, 52,899 followers.','self_published','subject_authored','https://x.com/sarahtavel','x.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_010','m_tavel','On her mother, in her own words: "Happy Mother''s Day to all the moms out there, esp (for me!) @susavel. ❤️ Immigrated to the US from Argentina in 1973 with a suitcase, $200, and one share of IBM stock. Lived the American dream. Raised five kids. Grateful to her, and to this country for making it possible."','self_published','subject_authored','https://x.com/sarahtavel','x.com','2021-05-09','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_011','m_tavel','Argues for stablecoins from family experience: "Another way to look at crypto to get you out of US-centric thinking: We''re used to looking at crypto prices in USD. Imagine if you have a high-inflation local currency (like my family in Argentina). This is Bitcoin in Argentine Pesos." In the same thread: "To be clear, what people want in Argentina is a USD... it''s the king. But my point is more that looking at Bitcoin in terms of local currency also lends more credence to crypto. Helps people get more curious / comfortable with USD stablecoins."','self_published','subject_authored','https://x.com/sarahtavel','x.com','2024-01-24','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_012','m_tavel','Why the blog is quiet, from her own X account, quoting Farhan Thawar quoting Kevin Kelly ("The most common mistake we make is to do a great job on an unimportant task"): "The secret fear they keeps making my blog post draft list longer and longer. 🤣"','self_published','subject_authored','https://x.com/sarahtavel','x.com','2026-08-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_013','m_tavel','"I have no connection to @fortellresearch but having read about them, I gifted my mom their hearing aids and it''s been a game changer for her. Only problem is she''s more excited about being able to eavesdrop on people''s conversations in the gym than hear us when out to dinner. :)"','self_published','subject_authored','https://x.com/sarahtavel','x.com','2026-08-12','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_014','m_tavel','She is not dormant. Her own X timeline carries posts on 2026-08-31 ("Love the two week follow up question of what name people remembered"), 2026-08-30, 2026-08-20 ("So much wisdom here on references. Thank you @dittycheria for continuing to share yours!"), 2026-08-12 and 2026-07-18 — the newest three days before this run, while her blog had been silent for twelve months.','self_published','subject_authored','https://x.com/sarahtavel','x.com','2026-08-31','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_015','m_tavel','Replied to Fred Wilson, once, on X — to @danprimack and @fredwilson: "great interview". This is the only appearance of the handle @fredwilson anywhere in her own X output.','self_published','subject_authored','https://x.com/sarahtavel','x.com','2016-02-08','2026-09-03T23:55:00Z',NULL,1,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_016','m_tavel','Replied to Josh Kopelman (@joshk) twice on X: "wow that was pretty good" (2016-08-21) and "great way of putting it" (2019-01-11).','self_published','subject_authored','https://x.com/sarahtavel','x.com','2019-01-11','2026-09-03T23:55:00Z',NULL,1,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_017','m_tavel','Hunter Walk is the one member of the room she talks TO, repeatedly and casually, over seven years of X replies: "Not too much of a break please. I depend on his social validation of my tweets. Happy birthday Hunter!" (2020-09-18); "The three squares is my recipe for happiness too! So glad you are enjoying." (2020-10-11); "you are funny" (2020-10-05); "jelly" (2020-05-12); "spurts indeed! thanks for including it. :)" (2023-09-05). Earlier, in 2016, she quoted a Valleywag headline at him: "Greylock, Khosla fight. Homebrew stuck in the middle. ''Who me?'' Asks Hunter Walk."','self_published','subject_authored','https://x.com/sarahtavel','x.com','2023-09-05','2026-09-03T23:55:00Z',NULL,1,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── every.to — public transcript. She spoke the words; Every published them ───
('f_tavel_018','m_tavel','Names her own board seats on the record: "I''m on the board of a company called Agentio, which is a marketplace for YouTube creators and brands... this has been a market that has eluded startups for a long time because most of them have kind of fallen into the quicksand of becoming an agency." And: "I''m on the board of a company called Chainalysis, so I''ve had a kind of seat in the crypto space and have been a long-term believer in Bitcoin."','on_record','subject_authored','https://every.to/podcast/transcript-c09360f3-efda-4688-952d-203b9f5f4315','every.to','2025-04-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_019','m_tavel','"My mom''s from Argentina and I can tell you everybody in Argentina wants a U.S. dollar. But it''s really hard to get them... I remember going to Argentina and having somebody on a motorcycle come to exchange money. That''s kind of what you would do."','on_record','subject_authored','https://every.to/podcast/transcript-c09360f3-efda-4688-952d-203b9f5f4315','every.to','2025-04-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_020','m_tavel','Carries a line from her Bessemer years as her test of a good board: "When I was at Bessemer, Jeremy Levine said that the best companies you want to be donut companies where you go to the board meeting, you eat a donut, and then you leave because they don''t really need you."','on_record','subject_authored','https://every.to/podcast/transcript-c09360f3-efda-4688-952d-203b9f5f4315','every.to','2025-04-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_021','m_tavel','Her stated taste in founders: "there''s some founders that it''s almost like a cool new job for them. And there''s some for whom it''s an affliction. And I''m attracted to the founders for whom it''s an affliction. You know, it''s this rash that they just have to scratch and that''s gonna make them run through whatever walls that they have to." And the tell she watches for: "I hate to say this, but they''re like, oh, that''s a good question. I hadn''t thought about that... That''s usually concerning."','on_record','subject_authored','https://every.to/podcast/transcript-c09360f3-efda-4688-952d-203b9f5f4315','every.to','2025-04-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_022','m_tavel','Keeps a written pre-mortem on every company she diligences, and names the source: "Annie Duke inspired this. She wrote this book Thinking in Bets. A pre-mortem — So every time I meet with a company and I dig in on it a little bit, I write to myself what I liked, what I didn''t like, what the deal would have been, and if I got yes, why? If I got no, why. And so it follows that over time, I''m gonna be able to look back on that list and examine my decision making process." She names one of her own misses in the same breath: "I know that there''s one example where I passed on a company because the valuation was too high. And that was a lesson to me of a company that ended up being a real success, this company Mercado."','on_record','subject_authored','https://every.to/podcast/transcript-c09360f3-efda-4688-952d-203b9f5f4315','every.to','2025-04-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_023','m_tavel','On localising Pinterest, and the piece of advice from Ben Silbermann she still uses: "I remember when I was at Pinterest and I was responsible for all the discovery experiences and very early on I had to kind of localize Pinterest... I was thinking about the categories and all as being different. I remember Ben saying to me, just assume it''s gonna be more similar than different."','on_record','subject_authored','https://every.to/podcast/transcript-c09360f3-efda-4688-952d-203b9f5f4315','every.to','2025-04-30','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── LinkedIn, SESSION (operator machine, logged in). Whitelist only ──────────
('f_tavel_024','m_tavel','Harvard University, A.B. in Philosophy, cum laude. Under Activities and societies, in her own words: "Captain of Women''s Rugby Team as a sophomore. Sold a lot of ads for Harvard Student Agencies. Honor''s thesis on Kantian ethics and autonomy."','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_025','m_tavel','Her whole entry for high school, verbatim: "Stuyvesant High School — Nerd amongst nerds."','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_026','m_tavel','Her first job out of college: Consultant, The Kerdan Group, Jun 2005 – Mar 2006 — "Strategy consultant in start up firm specializing in life sciences." Her working life therefore begins in 2005.','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_027','m_tavel','Vice President, Bessemer Venture Partners, May 2006 – Apr 2012, Menlo Park — six years, the longest run of her career. Her own deal list: "Convertro (acq), CPower (acq), Cornerstone OnDemand (IPO), Diapers.com/Quidsi (acq), KupiVIP, Metalogix (acq), MindBody (IPO), Onestop Internet, Pinterest (IPO), and Yodle (acq)."','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_028','m_tavel','Product Manager, Pinterest, Apr 2012 – Jul 2015: "Joined as a ''utility player'' before we had product managers, and became the first PM at Pinterest. Led product for all of our discovery experiences (search, recommendations, home feed, visual search, etc). I also led three acquisitions, launched us internationally, and was responsible for closing our $100m Series C financing. Ben Silbermann and Evan Sharp are two of the best humans and leaders out there."','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_029','m_tavel','General Partner, Greylock Partners, Sep 2015 – May 2017: "While at Greylock, I led Greylock''s investments in Sonder (Series B, IPO $SOND) and Gixo (Seed, acq. by Beachbody), and represented Greylock on the board of both companies." Twenty-one months — the shortest posting of her career.','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_030','m_tavel','Partner, Benchmark, May 2017 – present. Her own board list, as written: "Board member for Chainalysis, Hipcamp, Medely, Rekki, Glide, Cambly, 11x, Agentio, Eigen." Headline "Partner at Benchmark"; location San Francisco, California, United States.','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_031','m_tavel','38,047 LinkedIn followers, and an active feed: her own post five months before this run — "Captures Arthur Leopold''s intensity! ''If you work two hours more per day, you have five quarters when everyone else has four.'' Great listen." — and reposts of her portfolio founders (Agentio, 11x, Eigen) dated as recently as one week before it.','self_published','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── Instagram, SESSION. Profile metadata readable; the grid is HERS to close ──
('f_tavel_032','m_tavel','Instagram bio, verbatim: "Native New Yorker. SF transplant. Co-founder with @cklemke of @marcotavel." 119 posts, 623 followers, 358 following — and the account is PRIVATE ("This profile is private"), so no caption, location tag or post date is obtainable even from a logged-in session.','self_published','subject_authored','https://www.instagram.com/sarahtavel/','instagram.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── SEC EDGAR. CIK binds the name: named_in_sec_filing is STRONG here ────────
('f_tavel_033','m_tavel','SEC CIK 0001774645 is "Tavel Sarah E" — 17 filings, all Forms 3, 4 and 5, from 2021-06-23 to 2022-12-02. A Form 3 footnote binds her to the firm in the SEC''s own words: "Eric Vishria... Matthew R. Cohler, Peter H. Fenton, J. William Gurley, An-Yen Hu, Mitchell H. Lasky, Chetan Puttagunta, Steven M. Spurlock and Sarah E. Tavel are the managing members of BCMC VIII" — Benchmark Capital Management Co. VIII, L.L.C.','on_record','publisher','https://www.sec.gov/Archives/edgar/data/1774645/000089924321036831/doc3.xml','sec.gov','2021-09-21','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_034','m_tavel','Every one of her 17 filings reports her as a ten percent owner and NOT a director (isDirector=0), across three issuers: Confluent (CFLT), Amplitude (AMPL) and Nextdoor Holdings (KIND). The holdings are the fund''s — "Shares are held by Benchmark Capital Partners VIII, L.P." — and she disclaims beneficial ownership. Her SEC trail stops on 2022-12-02; the boards she actually sits on are private companies and appear nowhere in EDGAR.','on_record','publisher','https://data.sec.gov/submissions/CIK0001774645.json','data.sec.gov','2022-12-02','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── adventurista.com via Wayback — the mine. 103/103 fetched, 0 failures ─────
('f_tavel_035','m_tavel','Her first blog post ever, 2006-12-03, "It''s time to start blogging....", gives both reasons in her own voice: "there are a lot of new ''pre-MBA'' positions in Venture Capital (my position included)... there is a whole lot of misunderstanding out there about why these young kids are moving into VC-land"; and "there continues to be an amazing dearth of women and minorities in venture capital and start ups. For example, currently I am the only female in my firm of 30... Being an empowered woman (aka feminist), and having been involved in feminist organizations in college, I am inclined (make that, starved) to talk about these things."','self_published','subject_authored','https://web.archive.org/web/20071217162602/http://www.adventurista.com/2006/12/its-time-to-start-blogging.html','adventurista.com','2006-12-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_036','m_tavel','The "-ista" is a deliberate feminist joke, and she says so: "Because I initially started my blog with the intention of blogging from the perspective of a female, junior professional (hence the ''ista'' in Adventurista)". Her label cloud carried it through: "La Feminista (12)" and "La Environmentalista (5)" were the two biggest tags on the blog.','self_published','subject_authored','https://web.archive.org/web/20091103004637/http://www.adventurista.com/2009/09/my-ista-take-on-larry-chengs-vc-blog.html','adventurista.com','2009-09-09','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_037','m_tavel','Her own About Me blurb on the blog, c. 2011: "I grew up in NYC. While in college I became a Kant fanatic and, despite my parents'' best wishes, majored in Philosophy. I now work for Bessemer Venture Partners as a Senior Associate. Before Bessemer, I founded and ran a general contracting business (don''t ask), sold a lot of local ads for random small businesses, and was a strategy consultant. I was also captain of Harvard''s varsity women''s rugby team, so watch out. I still know how to tackle." The blog''s standing tagline, under it: "don''t mess with me".','self_published','subject_authored','https://web.archive.org/web/20110321005110/http://www.adventurista.com/2011/03/big-thank-you-to-cornerstone-ondemand.html','adventurista.com','2011-03-21','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_038','m_tavel','A whole post, 2009-04-16, is one line about rugby: "This video made me miss my rugby days. (The ''try'' starts at second 40.) I can''t believe I played for four years..." Filed under Personal.','self_published','subject_authored','https://web.archive.org/web/20090513085440/http://www.adventurista.com/2009/04/this-video-made-me-miss-my-rugby-days.html','adventurista.com','2009-04-16','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_039','m_tavel','On Harvard''s gender economics, from the inside of it: "don''t get me started about the rugby team! The men''s team was founded 100 years before the women''s team, so the women''s team is forever the poor, car-pooling cousin of our richer coach-bus male counterparts... when the discrepancy between women and men''s organizations is almost an institutional truth, it is all too obvious that there is still a long way to go at Harvard towards gender equality."','self_published','subject_authored','https://web.archive.org/web/20071217162652/http://www.adventurista.com/2007/02/harvard-soon-to-elect-first-female.html','adventurista.com','2007-02-09','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_040','m_tavel','A six-year callback, entirely inside her own blog. December 2006, on getting a junior VC job: "Not just because it means that I get to work in VC (Whoo hoo! Corporate Jet!)". March 2012, hiring her own replacement: "A lot of people want to work in VC for the wrong reasons. I regret to inform you that Bessemer does not have a corporate jet. Instead, a big part of this job is about getting out there in the community and networking to develop relationships with entrepreneurs."','self_published','subject_authored','https://web.archive.org/web/20120316012453/http://www.adventurista.com/2012/03/hiring-associate-at-bessemer.html','adventurista.com','2012-03-12','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_041','m_tavel','Fred Wilson is the only VC she cites repeatedly on Adventurista, and every citation is about BLOGGING or about how a VC should behave, never about a deal. "Fred Wilson is our Marc Benioff" (2009-11-23, on VC blogging as a freemium product); "Larry Cheng updated his popular VC Blog Ranking and included some fun analysis, particularly on how Fred Wilson continues to lead the VC blogging show" (2009-09-09); "I often find that picking a topic to write about is the hardest thing about blogging consistently (I don''t know how Fred Wilson does it). And as anyone who is a subscriber to my blog knows.... I''m not exactly a consistent blogger." (2010-06-29); and a whole post answering one of his — "Fred Wilson has a post on his blog about not doing a full pitch on the phone. I agree with Fred and the many commenters that in person meetings trump phone call pitches, but lest Fred''s advice be taken to the extreme, please don''t avoid them all together." (2010-07-20).','self_published','subject_authored','https://web.archive.org/web/20100723024639/http://www.adventurista.com/2010/07/in-defense-of-phone-call-pitches.html','adventurista.com','2010-07-20','2026-09-03T23:55:00Z',NULL,1,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_042','m_tavel','Cites Hunter Walk by name, once, in the second-to-last Adventurista post: "Hunter Walk reminded me that in a zero-sum world of only so many minutes in a day, blank spaces to absorb those minutes must come from cannibalizing other minutes, either from online or offline. When the smartphone was new, it was a lot easier to steal offline minutes and bring them online. Now, these opportunities are harder to find."','self_published','subject_authored','https://web.archive.org/web/20151012010918/http://www.adventurista.com/2015/10/times-have-changedgoing-after-dollars.html','adventurista.com','2015-10-05','2026-09-03T23:55:00Z',NULL,1,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_043','m_tavel','How she actually sourced her first big win, told the day it went public: "Early on, I came across Cornerstone OnDemand... I reached out to Adam, Cornerstone''s CEO... I started with a voicemail, and when I didn''t hear back, an email, and then another voicemail, and another voicemail... four more voicemails and one more email later, I finally tracked Adam down." She then introduced him to her Bessemer colleague Byron Deeter. Cornerstone IPO''d on 2011-03-17 at $13.00 and closed 47% up at $19.07, an $885m market cap.','self_published','subject_authored','https://web.archive.org/web/20110321005110/http://www.adventurista.com/2011/03/big-thank-you-to-cornerstone-ondemand.html','adventurista.com','2011-03-17','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_044','m_tavel','Wrote about Argentine politics through her parents, in 2007: "Let''s just say my parents are not Hillary Clinton fans... my Mom can''t stand her because her campaign brings back too many bad memories of Argentinean politics... The Mom: ''It''s the same corrupt Argentinean politics that we saw with Evita Peron.''" Filed under her single Argentina tag.','self_published','subject_authored','https://web.archive.org/web/20071217162911/http://www.adventurista.com/2007/07/echoes-of-argentine-politics-in-us.html','adventurista.com','2007-07-07','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_045','m_tavel','Bought her own domain because a friend told her to: "More than a month ago, my friend Charlie sent me an important email. I believe the subject of the email was ''You should grab your domain!!!!!''... Spurred to action, I went to GoDaddy.com and picked up www.adventurista.com. As it happens, a couple of weeks later, I got another email in which someone offered me $200 for the domain."','self_published','subject_authored','https://web.archive.org/web/20071217162914/http://www.adventurista.com/2007/07/moving-adventurista-to-permanent-home.html','adventurista.com','2007-07-22','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_046','m_tavel','Ranked her own blog inside a public VC blog ranking, and split it two ways for the people she cared about: "Junior Professionals (woot woot!)" and "The Ladies (oh yeah!)" — where she placed herself second of three: "Sarah Tavel, Bessemer Venture Partners, Adventurista (156)". Her rule for the junior list: "if a person didn''t have the words ''Partner'' or ''Managing'' in their LinkedIn or website bio, I included them."','self_published','subject_authored','https://web.archive.org/web/20091103004637/http://www.adventurista.com/2009/09/my-ista-take-on-larry-chengs-vc-blog.html','adventurista.com','2009-09-09','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_047','m_tavel','Adventurista, measured rather than estimated: 104 distinct post URLs recovered from Wayback, dated 2006-12-03 to 2015-10-07 — five in 2006, thirty-seven in 2007, eleven in 2008, sixteen in 2009, twenty-two in 2010, eight in 2011, two in 2012, then a three-and-a-half-year gap and two final posts in October 2015. The blog was retitled twice as she was promoted: "Adventurista", then "Sarah Tavel / Adventurista", and by 2015 it carried the subtitle "Old school blogger...".','self_published','subject_authored','http://web.archive.org/cdx/search/cdx?url=adventurista.com*&filter=statuscode:200&filter=mimetype:text/html&collapse=urlkey','adventurista.com','2015-10-07','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── benchmark.com — the firm that publishes nothing ──────────────────────────
('f_tavel_048','m_tavel','Her firm publishes nothing about her. benchmark.com is 2,297 bytes total: a logo, two addresses (140 New Montgomery Street, San Francisco CA 94105 and 2965 Woodside Road, Woodside CA 94062) and a link to @benchmark. There are no partner bios, no blog and no feed; /people is a 404.','on_record','publisher','https://www.benchmark.com/','benchmark.com','2026-09-03','2026-09-03T23:55:00Z',NULL,0,NULL,NULL,'run_ingest_tavel_20260903'),

-- ── inferred: composed_from is mandatory and populated ───────────────────────
('f_tavel_049','m_tavel','Her working life starts in 2005 — Kerdan Group, June 2005 — which puts her career_start_decade at 2000s. Her own bio says "Blogging since 2006", and her first post, December 2006, describes her as already holding a "pre-MBA" VC position, which is consistent with Bessemer from May 2006.','inferred','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z','["f_tavel_026","f_tavel_027","f_tavel_035","f_tavel_007"]',0,NULL,NULL,'run_ingest_tavel_20260903'),

('f_tavel_050','m_tavel','Twenty years apart, two independently written sources say the same three things about her college years, which is why they are safe to render: her 2011 blog blurb ("a Kant fanatic and, despite my parents'' best wishes, majored in Philosophy... captain of Harvard''s varsity women''s rugby team") and her 2026 LinkedIn education entry ("A.B., Philosophy (cum laude)... Captain of Women''s Rugby Team as a sophomore... Honor''s thesis on Kantian ethics and autonomy").','inferred','subject_authored','https://www.linkedin.com/in/sarahtavel/','linkedin.com','2026-09-03','2026-09-03T23:55:00Z','["f_tavel_024","f_tavel_037"]',0,NULL,NULL,'run_ingest_tavel_20260903');

COMMIT;
