PRAGMA foreign_keys = ON;
BEGIN;

INSERT INTO run (id, started_at, execution_ctx, notes) VALUES
  ('run_ingest_walk_20260903','2026-09-04T01:25:00Z','operator_machine',
   'Hunter Walk sidecar ingest in progress. Facts are loaded in this transaction; edges, contexts, source attempts, final counts, and finished_at are applied by m_walk-02-edges-contexts-status.sql.');

UPDATE person
   SET career_start_decade='1990s'
 WHERE id='m_walk';

INSERT OR IGNORE INTO person_identity
  (person_id,source_id,url,handle,role,tier,corroboration,http_status,measured_at,notes)
VALUES
  ('m_walk','canonical_about','https://hunterwalk.com/about/','hunterwalk','canonical','GREEN','["subject_self_identifies"]',200,'2026-09-03',
   'First-party biography; directly links LinkedIn /in/hunterwalk, Homebrew, Screendoor, Instagram, Bluesky, and Threads.'),
  ('m_walk','blog_five_questions','https://hunterwalk.com/wp-json/wp/v2/posts?search=Five%20Questions%20With','hunterwalk','api','GREEN','["subject_self_identifies"]',200,'2026-09-03',
   'WordPress REST search returned 103 posts across two pages. Only clearly titled interview subjects were converted to edges.'),
  ('m_walk','linkedin_session','https://www.linkedin.com/in/hunterwalk/','hunterwalk','canonical','SESSION','["linked_from_own_canonical","bio_backlink_to_canonical","subject_self_identifies"]',200,'2026-09-03',
   'Slug came from hunterwalk.com/about. Read live and read-only in the operator Chrome session; headline, location, company, school, follower count, experience, and public activity were extracted. Personalization and write affordances were stripped.'),
  ('m_walk','linkedin_wayback','http://web.archive.org/web/20250806163838/https://www.linkedin.com/in/hunterwalk','hunterwalk','archive','GREEN','["linked_from_own_canonical","bio_backlink_to_canonical","display_name_matches"]',200,'2026-09-03',
   'Wayback availability API identified snapshot 20250806163838; archived HTML linked hunterwalk.com and named Homebrew and Screendoor.'),
  ('m_walk','homebrew_blog','https://www.homebrew.co/blog',NULL,'firm','GREEN','["linked_from_own_canonical"]',200,'2026-09-03',
   'Separate firm-news corpus. Page exposes no article byline; no article text was attributed to Walk.'),
  ('m_walk','leanpub_uncensored','https://leanpub.com/uncensored','hunterwalk','canonical','GREEN','["subject_self_identifies"]',200,'2026-09-03',
   'Publisher metadata names Hunter Walk and Eric Ries as authors and enumerates contributors including Wilson, Feld, and Kopelman.');

INSERT INTO fact
  (id,subject_id,text,provenance_class,trust_class,source_url,source_host,source_date,observed_at,composed_from,search_first_page,via_edge_type,via_person_id,run_id)
VALUES
  ('f_walk_001','m_walk',
   'Walk describes himself as a Partner at Homebrew, says it is a seed-stage venture firm serving founders, says he also backs new venture firms through Screendoor, and says he lives in San Francisco.',
   'self_published','subject_authored','https://hunterwalk.com/about/','hunterwalk.com','2026-09-03','2026-09-04T01:28:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_002','m_walk',
   'His first-party biography says he led consumer product management at YouTube, joined Google in 2003, was a founding product-and-marketing team member at Linden Lab, earlier worked as a management consultant and at Late Night with Conan O’Brien, and earned degrees from Vassar and Stanford.',
   'self_published','subject_authored','https://hunterwalk.com/about/','hunterwalk.com','2026-09-03','2026-09-04T01:28:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_003','m_walk',
   'Read live in the operator’s Chrome session, LinkedIn showed Hunter Walk with the headline “Funding Startups via Homebrew and new VCs via Screendoor LP,” location San Francisco, current company Homebrew, Stanford Graduate School of Business, and a link back to hunterwalk.com.',
   'self_published','subject_authored','https://www.linkedin.com/in/hunterwalk/','linkedin.com','2026-09-03','2026-09-04T01:32:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_004','m_walk',
   'LinkedIn showed 882,825 followers on 2026-09-03. This is higher than the seeded X-based prominence basis, but the parallel overlay leaves the seeded prominence tier and basis unchanged for merge safety.',
   'on_record','publisher','https://www.linkedin.com/in/hunterwalk/','linkedin.com','2026-09-03','2026-09-04T01:32:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_005','m_walk',
   'LinkedIn experience lists Homebrew from January 2013, Screendoor from July 2021, Google from November 2003 to February 2013, Linden Lab from January 2001, Mattel in 1999, Deloitte Consulting from August 1995, and Late Night with Conan O’Brien at NBC from September 1994 to June 1995. The 1994 start supports career_start_decade=1990s.',
   'self_published','subject_authored','https://www.linkedin.com/in/hunterwalk/details/experience/','linkedin.com','2026-09-03','2026-09-04T01:33:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_006','m_walk',
   'LinkedIn loaded 20 public activity posts; the newest visible item was two days old on 2026-09-03 and read “Every zoom, podcast recording, etc etc,” establishing current activity rather than silence.',
   'self_published','subject_authored','https://www.linkedin.com/in/hunterwalk/recent-activity/all/','linkedin.com',NULL,'2026-09-04T01:34:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_007','m_walk',
   'In a public LinkedIn post, Walk wrote “my wife Caroline Barlerin inspires me in many many ways” and linked Caroline Barlerin’s profile.',
   'self_published','subject_authored','https://www.linkedin.com/posts/hunterwalk_my-wife-caroline-barlerin-inspires-me-in-activity-7383298468481728512--vHq','linkedin.com','2025-10-13','2026-09-04T01:41:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_008','m_walk',
   'The 2025-08-06 archived LinkedIn profile names Hunter Walk, Homebrew, Screendoor, San Francisco, Stanford, and Vassar; its structured profile data records employment back to NBC in September 1994 and 875,783 followers.',
   'on_record','publisher','http://web.archive.org/web/20250806163838/https://www.linkedin.com/in/hunterwalk','web.archive.org','2025-08-06','2026-09-04T01:31:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_009','m_walk',
   'The WordPress REST API reported 1,761 lifetime posts for hunterwalk.com.',
   'on_record','publisher','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=1','hunterwalk.com','2026-09-03','2026-09-04T01:38:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_010','m_walk',
   'The WordPress API returned 27 posts after 2026-03-01. The newest, published 2026-08-30, discusses Clay’s public AI writing policy and its principles that writers must stand behind every idea and sentence and treat writing as thinking.',
   'self_published','subject_authored','https://hunterwalk.com/2026/08/30/does-your-startup-have-an-ai-writing-policy-yet-heres-one-from-clay/','hunterwalk.com','2026-08-30','2026-09-04T01:38:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_011','m_walk',
   'The WordPress REST search for “Five Questions With” returned 103 posts across two pages. The result set includes interviews and unrelated posts containing the phrase, so only titles that clearly name an interview subject were used as relationship evidence.',
   'on_record','publisher','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2026-04-01','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_012','m_walk',
   'Bluesky’s public profile API resolved hunterwalk.com to a profile whose display name is “👨🏻‍💻☕️,” whose bio links hunterwalk.com, and which had 5,370 followers and 573 posts when checked.',
   'self_published','subject_authored','https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor=hunterwalk.com','public.api.bsky.app','2026-09-03','2026-09-04T01:38:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_013','m_walk',
   'Walk was active on Bluesky through 2026-09-02; that day his own posts included “#coffeewithhunter,” a dog update, and replies about sports and politics.',
   'self_published','subject_authored','https://bsky.app/profile/hunterwalk.com/post/3mujvexmq4k2g','bsky.app','2026-09-02','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_014','m_walk',
   'GitHub’s user API returns login hunterwalk, name Hunter Walk, blog www.hunterwalk.com, and zero public repositories. This confirms a claimed handle but not a code presence.',
   'on_record','publisher','https://api.github.com/users/hunterwalk','api.github.com','2026-09-03','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_015','m_walk',
   'The sanctioned X profile measurement endpoint returned 246,607 followers, 10 following, and one tweet for @hunterwalk. That is four followers below the seeded 246,611 measurement; the seed was not updated.',
   'on_record','publisher','https://api.fxtwitter.com/hunterwalk','api.fxtwitter.com','2026-09-03','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_016','m_walk',
   'The @hunterwalk X profile links hunterwalk.com and its bio names @homebrew, @screendoorvc, @cbarlerin after a family emoji, and @daisyfleets after a dog emoji. The display name is the same “👨🏻‍💻☕️” string used on his confirmed Bluesky account.',
   'self_published','subject_authored','https://api.fxtwitter.com/hunterwalk','api.fxtwitter.com','2026-09-03','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_017','m_walk',
   'The confirmed Hunter Walk YouTube feed identifies the channel as Hunter Walk, dates its creation to 2006-01-03, and contains 15 videos published from 2012 through 2024.',
   'on_record','publisher','https://www.youtube.com/feeds/videos.xml?channel_id=UC68ai6rdol6MOTe_4b6T-wQ','youtube.com','2006-01-03','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_018','m_walk',
   'His YouTube feed is dominated by crowd-shot live music: titles include “Wake me up when September ends” and “Green Day so good” from the Fillmore in 2024, Bush at the Warfield, Guns N’ Roses songs, Jane’s Addiction, Pink and No Doubt, Linkin Park, and Green Day.',
   'self_published','subject_authored','https://www.youtube.com/feeds/videos.xml?channel_id=UC68ai6rdol6MOTe_4b6T-wQ','youtube.com','2024-04-27','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_019','m_walk',
   'Leanpub identifies Hunter Walk and Eric Ries as the authors of Uncensored and enumerates Fred Wilson, Brad Feld, Josh Kopelman, Ries, and Walk among its contributors, placing five arena members in one artifact.',
   'on_record','publisher','https://leanpub.com/uncensored','leanpub.com','2012-02-23','2026-09-04T01:36:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_020','m_walk',
   'Walk wrote, “In January Eric Ries and I curated an ebook called Uncensored,” and said it featured posts from Fred Wilson, Brad Feld, and dozens of other technologists to benefit the Electronic Frontier Foundation.',
   'self_published','subject_authored','https://hunterwalk.com/2012/03/04/uncensoredbook-now-free-to-all-eff-supporters/','hunterwalk.com','2012-03-04','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_021','m_walk',
   'Brad Feld wrote that he and his Foundry partners were investors in Homebrew and that Hunter Walk and Satya Patel spent a full day working with the Foundry partners in Boulder.',
   'third_party','publisher','https://feld.com/archives/2014/05/spending-day-another-vc-firm/','feld.com','2014-05-27','2026-09-04T01:36:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_022','m_walk',
   'Walk announced Homebrew as “a seed stage venture fund created by me and my good friend Satya Patel,” designed to back entrepreneurs in the Bottom Up Economy.',
   'self_published','subject_authored','https://hunterwalk.com/2013/07/17/announcing-homebrew-a-seed-stage-fund-for-the-bottom-up-economy/','hunterwalk.com','2013-07-17','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_023','m_walk',
   'After 13 years in early-stage venture, Walk argued in 2026 that funds of $100 million or less should minimize reserves, evaluate every pro-rata opportunity against a new investment, and seek more initial shots on goal.',
   'self_published','subject_authored','https://hunterwalk.com/2026/07/23/ive-changed-my-mind-early-stage-venture-funds-of-100-million-or-less-should-hold-almost-no-reserves-for-follow-on/','hunterwalk.com','2026-07-23','2026-09-04T01:39:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_024','m_walk',
   'Walk named Josh Kopelman one of the most influential VCs of the 2010s and credited Kopelman and First Round Capital with institutionalizing seed financing, building a platform model early, and becoming a bellwether for generational transition in seed VC.',
   'self_published','subject_authored','https://hunterwalk.com/2019/12/16/the-five-most-influential-vcs-of-the-2010s/','hunterwalk.com','2019-12-16','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_025','m_walk',
   'Walk argues that a good startup board is “10x better than no Board and a bad Board is 10x worse,” recommends adding an outside director by Series A or B, and cites Brad Feld on the value of excellent outside directors.',
   'self_published','subject_authored','https://hunterwalk.com/2017/01/07/once-youve-raised-a-series-a-add-an-outside-director/','hunterwalk.com','2017-01-07','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_026','m_walk',
   'Walk wrote that he co-signed a 2016 technology-industry letter opposing Donald Trump, committed time and money to Hillary Clinton’s campaign, and connected innovation policy to immigration, expression, research, and infrastructure.',
   'self_published','subject_authored','https://hunterwalk.com/2016/07/14/trump-would-hurt-innovation-im-with-her/','hunterwalk.com','2016-07-14','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_027','m_walk',
   'On the ten-year anniversary of therapy, Walk wrote that anxiety and depression in 2011 convinced him to seek a therapist and that he had continued seeing him for ten years.',
   'self_published','subject_authored','https://hunterwalk.com/2021/10/02/celebrating-10-years-of-therapy/','hunterwalk.com','2021-10-02','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_028','m_walk',
   'Walk calls his long-running fear metaphor the “failure tiger.” In 2019 he wrote that it had chased him through his 20s and 30s and that parenting, his wife’s support, therapy, and financial security had left him free of it for roughly seven years.',
   'self_published','subject_authored','https://hunterwalk.com/2019/12/19/how-i-calmed-the-failure-tiger-nipping-at-my-heels/','hunterwalk.com','2019-12-19','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_029','m_walk',
   'Walk wrote that his Instagram feed was purposefully dominated by coffee cups and paper notebooks, then published lists of favorite coffee and notebook-art accounts.',
   'self_published','subject_authored','https://hunterwalk.com/2017/11/06/my-favorite-instagram-accounts-coffee-and-notebooks/','hunterwalk.com','2017-11-06','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_030','m_walk',
   'Walk says his first concert was Madonna’s Like a Virgin Tour at Radio City Music Hall in June 1985; the Beastie Boys opened, the crowd booed them, and he later became a longtime fan. He adds, “I really do love live music.”',
   'self_published','subject_authored','https://hunterwalk.com/2022/04/28/what-was-the-first-concert-you-attended%ef%bf%bc/','hunterwalk.com','2022-04-28','2026-09-04T01:35:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_031','m_walk',
   'Walk cited Sarah Tavel in a 2025 link post on how B2B AI startups can defend against evolving LLM platforms.',
   'self_published','subject_authored','https://hunterwalk.com/2025/03/18/men-spend-more-time-with-tv-than-with-people-founder-gives-away-half-his-wealth-to-progressive-causes-a-vc-thinks-the-llms-are-going-to-try-and-eat-saas-the-ai-prompts-that-saved-a-life-link/','hunterwalk.com','2025-03-18','2026-09-04T01:45:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_032','m_walk',
   'A targeted WordPress REST search across the 1,761-post archive returned zero posts for “Steve Huffman.” This supports only a blog-corpus absence, not a universal claim that Walk has no relationship with Huffman.',
   'on_record','publisher','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Steve%20Huffman','hunterwalk.com','2026-09-03','2026-09-04T01:44:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_033','m_walk',
   'A targeted WordPress REST search across the 1,761-post archive returned zero posts for “Emmett Shear.” This supports only a blog-corpus absence, not a universal claim that Walk has no relationship with Shear.',
   'on_record','publisher','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Emmett%20Shear','hunterwalk.com','2026-09-03','2026-09-04T01:44:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_034','m_walk',
   'A targeted WordPress REST search across the 1,761-post archive returned zero posts for “Melanie Perkins.” This supports only a blog-corpus absence, not a universal claim that Walk has no relationship with Perkins.',
   'on_record','publisher','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Melanie%20Perkins','hunterwalk.com','2026-09-03','2026-09-04T01:44:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_035','m_walk',
   'A targeted WordPress REST search across the 1,761-post archive returned zero posts for “Nabeel Qureshi.” This supports only a blog-corpus absence, not a universal claim that Walk has no relationship with Qureshi.',
   'on_record','publisher','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Nabeel%20Qureshi','hunterwalk.com','2026-09-03','2026-09-04T01:44:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_036','m_walk',
   'Interview posts in the 103-result corpus from 2024-2026 identify Dan Teran, Brad Hargreaves, Austin Johnsen, Jason Del Rey, Tom Preston-Werner, Alex Heath, Alex Konrad, Joe Hyrkin, Molly Mielke, Alex Levin, Nilam Ganenthiran, Ben Braverman, Sandro Roco, Javier Soltero, Max Greenwald, and Pat Kinsel.',
   'self_published','subject_authored','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2026-04-01','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_037','m_walk',
   'Interview posts in the corpus from 2020-2023 identify Melanie Naranjo, Michael Mignano, Chris Neumann, Avni Patel Thompson, Sar Haribhakti, Ashley Mayer, Jarrod Dicker, Andrew Bosworth, Alex Taub, Lenny Rachitsky, and Kia Kokalitcheva.',
   'self_published','subject_authored','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2023-08-31','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_038','m_walk',
   'Interview posts in the corpus from 2018-2019 identify Katie Carroll, Jeff Berman, Adam Davidson, Rebecca Hanover, Jason Shellen, Taylor Lorenz, Brian Morrissey, and Web Smith.',
   'self_published','subject_authored','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2019-08-19','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_039','m_walk',
   'Interview posts in the 2017 corpus identify Amber Discko, Christy Turlington Burns, Susan Lyne, Renee DiResta, Heather Hartnett, Nick Quah, Alyssa Bereznak, Casey Newton, Derek Nelson, and Tommy Vietor.',
   'self_published','subject_authored','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2017-08-19','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_040','m_walk',
   'Interview posts in the 2016 corpus identify Jennifer Pahlka, Brett Hagler, Amy Chang, Virginia Heffernan, Scott Harrison, Anneke Jong, Bianca St. Louis, Charles Best, Kyle Russell, Emily LaFave Olson, and Julia Boorstin.',
   'self_published','subject_authored','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2016-12-21','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_041','m_walk',
   'Additional 2016 interview posts in the corpus identify Elle Luna, Laura Weidman Powers, Vanessa Pappas, Jessi Hempel, Alec Ross, Adam Grant, Kimberly Newell Green, Sasha Lubomirsky, Ted Rheingold, and Shiva Rajaraman.',
   'self_published','subject_authored','https://hunterwalk.com/wp-json/wp/v2/posts?per_page=100&search=Five%20Questions%20With&page=1','hunterwalk.com','2016-02-21','2026-09-04T01:29:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903'),
  ('f_walk_042','m_walk',
   'In a directly fetched five-question interview published 2016-02-24, Alexia Tsotsis discussed leaving TechCrunch for Stanford’s Sloan program, learning the financial mechanics behind startups, editorial leadership, gender in journalism, and over- and under-covered technology topics.',
   'self_published','subject_authored','https://hunterwalk.com/2016/02/24/if-you-stop-learning-you-stop-living-why-alexia-tsotsis-left-techcrunch-for-stanford-bschool/','hunterwalk.com','2016-02-24','2026-09-04T02:08:00Z',NULL,0,NULL,NULL,'run_ingest_walk_20260903');

COMMIT;
